server:
  port: 8992

spring:
  application:
    name: gateway
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
    gateway:
      routes:
        - id: user_route
          #          uri: http://localhost:9999/
          uri: lb://users # lb：使用负载均衡策略  users代表注册中心的具体服务名
          predicates:
            - Path=/user/**,/feign/**

        - id: emps_route
          #          uri: http://localhost:9998/
          uri: lb://emps # lb：使用负载均衡策略  products代表注册中心的具体服务名
          predicates:
            - Path=/emp/**
#      解决跨域问题
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
        add-to-simple-url-handler-mapping: true

      discovery:
        locator:
          enabled: true # 开启根据动态服务名动态获取路由地址
management:
  endpoints:
    web:
      exposure:
        include: "*"  # 暴露所有的路由端点