server:
  port: 8081

spring:

  datasource:
    url: jdbc:mysql:///shiro?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 111111
    driver-class-name: com.mysql.cj.jdbc.Driver
#
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#mybatis-plus:
#  mapper-locations: classpath*:**/xml/*.xml
#  type-aliases-package: com.example.shiro.entity
#mybatis:
#  mapper-locations=classpath:com/*/*/*/mapper/*.xml:

mybatis-plus:
  type-aliases-package: com.example.shiro
  mapper-locations: classpath*:com/example/shiro/mapper/xml/*.xml
