package dao;

import bean.huiyuankaleixingBean;
import bean.huiyuankaleixingBeanExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class huiyuankaleixingBeanDAOImpl extends SqlMapClientDaoSupport implements huiyuankaleixingBeanDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table huiyuankaleixing
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public huiyuankaleixingBeanDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table huiyuankaleixing
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public int countByExample(huiyuankaleixingBeanExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("huiyuankaleixing.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table huiyuankaleixing
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public int deleteByExample(huiyuankaleixingBeanExample example) {
        int rows = getSqlMapClientTemplate().delete("huiyuankaleixing.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table huiyuankaleixing
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public int deleteByPrimaryKey(Integer id) {
        huiyuankaleixingBean key = new huiyuankaleixingBean();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("huiyuankaleixing.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table huiyuankaleixing
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void insert(huiyuankaleixingBean record) {
        getSqlMapClientTemplate().insert("huiyuankaleixing.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table huiyuankaleixing
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void insertSelective(huiyuankaleixingBean record) {
        getSqlMapClientTemplate().insert("huiyuankaleixing.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table huiyuankaleixing
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    @SuppressWarnings("unchecked")
    public List<huiyuankaleixingBean> selectByExample(huiyuankaleixingBeanExample example) {
        List<huiyuankaleixingBean> list = getSqlMapClientTemplate().queryForList("huiyuankaleixing.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table huiyuankaleixing
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public huiyuankaleixingBean selectByPrimaryKey(Integer id) {
        huiyuankaleixingBean key = new huiyuankaleixingBean();
        key.setId(id);
        huiyuankaleixingBean record = (huiyuankaleixingBean) getSqlMapClientTemplate().queryForObject("huiyuankaleixing.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table huiyuankaleixing
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public int updateByExampleSelective(huiyuankaleixingBean record, huiyuankaleixingBeanExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("huiyuankaleixing.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table huiyuankaleixing
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public int updateByExample(huiyuankaleixingBean record, huiyuankaleixingBeanExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("huiyuankaleixing.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table huiyuankaleixing
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public int updateByPrimaryKeySelective(huiyuankaleixingBean record) {
        int rows = getSqlMapClientTemplate().update("huiyuankaleixing.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table huiyuankaleixing
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public int updateByPrimaryKey(huiyuankaleixingBean record) {
        int rows = getSqlMapClientTemplate().update("huiyuankaleixing.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table huiyuankaleixing
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private static class UpdateByExampleParms extends huiyuankaleixingBeanExample {
        private Object record;

        public UpdateByExampleParms(Object record, huiyuankaleixingBeanExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}