package dao;

import bean.huiyuankaleixingBean;
import bean.huiyuankaleixingBeanExample;
import java.util.List;

public interface huiyuankaleixingBeanDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table huiyuankaleixing
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int countByExample(huiyuankaleixingBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table huiyuankaleixing
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int deleteByExample(huiyuankaleixingBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table huiyuankaleixing
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table huiyuankaleixing
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    void insert(huiyuankaleixingBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table huiyuankaleixing
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    void insertSelective(huiyuankaleixingBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table huiyuankaleixing
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    List<huiyuankaleixingBean> selectByExample(huiyuankaleixingBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table huiyuankaleixing
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    huiyuankaleixingBean selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table huiyuankaleixing
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int updateByExampleSelective(huiyuankaleixingBean record, huiyuankaleixingBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table huiyuankaleixing
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int updateByExample(huiyuankaleixingBean record, huiyuankaleixingBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table huiyuankaleixing
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int updateByPrimaryKeySelective(huiyuankaleixingBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table huiyuankaleixing
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int updateByPrimaryKey(huiyuankaleixingBean record);
}