package dao;

import bean.huiyuanxuankeBean;
import bean.huiyuanxuankeBeanExample;
import java.util.List;

public interface huiyuanxuankeBeanDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table huiyuanxuanke
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int countByExample(huiyuanxuankeBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table huiyuanxuanke
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int deleteByExample(huiyuanxuankeBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table huiyuanxuanke
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table huiyuanxuanke
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    void insert(huiyuanxuankeBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table huiyuanxuanke
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    void insertSelective(huiyuanxuankeBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table huiyuanxuanke
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    List<huiyuanxuankeBean> selectByExample(huiyuanxuankeBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table huiyuanxuanke
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    huiyuanxuankeBean selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table huiyuanxuanke
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int updateByExampleSelective(huiyuanxuankeBean record, huiyuanxuankeBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table huiyuanxuanke
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int updateByExample(huiyuanxuankeBean record, huiyuanxuankeBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table huiyuanxuanke
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int updateByPrimaryKeySelective(huiyuanxuankeBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table huiyuanxuanke
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int updateByPrimaryKey(huiyuanxuankeBean record);
}