package dao;

import bean.jiaolianxinxiBean;
import bean.jiaolianxinxiBeanExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class jiaolianxinxiBeanDAOImpl extends SqlMapClientDaoSupport implements jiaolianxinxiBeanDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table jiaolianxinxi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public jiaolianxinxiBeanDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table jiaolianxinxi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public int countByExample(jiaolianxinxiBeanExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("jiaolianxinxi.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table jiaolianxinxi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public int deleteByExample(jiaolianxinxiBeanExample example) {
        int rows = getSqlMapClientTemplate().delete("jiaolianxinxi.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table jiaolianxinxi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public int deleteByPrimaryKey(Integer id) {
        jiaolianxinxiBean key = new jiaolianxinxiBean();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("jiaolianxinxi.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table jiaolianxinxi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void insert(jiaolianxinxiBean record) {
        getSqlMapClientTemplate().insert("jiaolianxinxi.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table jiaolianxinxi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void insertSelective(jiaolianxinxiBean record) {
        getSqlMapClientTemplate().insert("jiaolianxinxi.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table jiaolianxinxi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    @SuppressWarnings("unchecked")
    public List<jiaolianxinxiBean> selectByExample(jiaolianxinxiBeanExample example) {
        List<jiaolianxinxiBean> list = getSqlMapClientTemplate().queryForList("jiaolianxinxi.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table jiaolianxinxi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public jiaolianxinxiBean selectByPrimaryKey(Integer id) {
        jiaolianxinxiBean key = new jiaolianxinxiBean();
        key.setId(id);
        jiaolianxinxiBean record = (jiaolianxinxiBean) getSqlMapClientTemplate().queryForObject("jiaolianxinxi.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table jiaolianxinxi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public int updateByExampleSelective(jiaolianxinxiBean record, jiaolianxinxiBeanExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("jiaolianxinxi.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table jiaolianxinxi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public int updateByExample(jiaolianxinxiBean record, jiaolianxinxiBeanExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("jiaolianxinxi.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table jiaolianxinxi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public int updateByPrimaryKeySelective(jiaolianxinxiBean record) {
        int rows = getSqlMapClientTemplate().update("jiaolianxinxi.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table jiaolianxinxi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public int updateByPrimaryKey(jiaolianxinxiBean record) {
        int rows = getSqlMapClientTemplate().update("jiaolianxinxi.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table jiaolianxinxi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private static class UpdateByExampleParms extends jiaolianxinxiBeanExample {
        private Object record;

        public UpdateByExampleParms(Object record, jiaolianxinxiBeanExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}