package dao;

import bean.jiaoliandengjiBean;
import bean.jiaoliandengjiBeanExample;
import java.util.List;

public interface jiaoliandengjiBeanDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table jiaoliandengji
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int countByExample(jiaoliandengjiBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table jiaoliandengji
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int deleteByExample(jiaoliandengjiBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table jiaoliandengji
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table jiaoliandengji
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    void insert(jiaoliandengjiBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table jiaoliandengji
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    void insertSelective(jiaoliandengjiBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table jiaoliandengji
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    List<jiaoliandengjiBean> selectByExample(jiaoliandengjiBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table jiaoliandengji
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    jiaoliandengjiBean selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table jiaoliandengji
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int updateByExampleSelective(jiaoliandengjiBean record, jiaoliandengjiBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table jiaoliandengji
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int updateByExample(jiaoliandengjiBean record, jiaoliandengjiBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table jiaoliandengji
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int updateByPrimaryKeySelective(jiaoliandengjiBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table jiaoliandengji
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int updateByPrimaryKey(jiaoliandengjiBean record);
}