package dao;

import bean.jiaoliandengjiBean;
import bean.jiaoliandengjiBeanExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class jiaoliandengjiBeanDAOImpl extends SqlMapClientDaoSupport implements jiaoliandengjiBeanDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table jiaoliandengji
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public jiaoliandengjiBeanDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table jiaoliandengji
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public int countByExample(jiaoliandengjiBeanExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("jiaoliandengji.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table jiaoliandengji
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public int deleteByExample(jiaoliandengjiBeanExample example) {
        int rows = getSqlMapClientTemplate().delete("jiaoliandengji.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table jiaoliandengji
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public int deleteByPrimaryKey(Integer id) {
        jiaoliandengjiBean key = new jiaoliandengjiBean();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("jiaoliandengji.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table jiaoliandengji
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void insert(jiaoliandengjiBean record) {
        getSqlMapClientTemplate().insert("jiaoliandengji.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table jiaoliandengji
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void insertSelective(jiaoliandengjiBean record) {
        getSqlMapClientTemplate().insert("jiaoliandengji.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table jiaoliandengji
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    @SuppressWarnings("unchecked")
    public List<jiaoliandengjiBean> selectByExample(jiaoliandengjiBeanExample example) {
        List<jiaoliandengjiBean> list = getSqlMapClientTemplate().queryForList("jiaoliandengji.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table jiaoliandengji
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public jiaoliandengjiBean selectByPrimaryKey(Integer id) {
        jiaoliandengjiBean key = new jiaoliandengjiBean();
        key.setId(id);
        jiaoliandengjiBean record = (jiaoliandengjiBean) getSqlMapClientTemplate().queryForObject("jiaoliandengji.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table jiaoliandengji
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public int updateByExampleSelective(jiaoliandengjiBean record, jiaoliandengjiBeanExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("jiaoliandengji.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table jiaoliandengji
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public int updateByExample(jiaoliandengjiBean record, jiaoliandengjiBeanExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("jiaoliandengji.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table jiaoliandengji
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public int updateByPrimaryKeySelective(jiaoliandengjiBean record) {
        int rows = getSqlMapClientTemplate().update("jiaoliandengji.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table jiaoliandengji
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public int updateByPrimaryKey(jiaoliandengjiBean record) {
        int rows = getSqlMapClientTemplate().update("jiaoliandengji.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table jiaoliandengji
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private static class UpdateByExampleParms extends jiaoliandengjiBeanExample {
        private Object record;

        public UpdateByExampleParms(Object record, jiaoliandengjiBeanExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}