package dao;

import bean.kechengleixingBean;
import bean.kechengleixingBeanExample;
import java.util.List;

public interface kechengleixingBeanDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table kechengleixing
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int countByExample(kechengleixingBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table kechengleixing
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int deleteByExample(kechengleixingBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table kechengleixing
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table kechengleixing
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    void insert(kechengleixingBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table kechengleixing
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    void insertSelective(kechengleixingBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table kechengleixing
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    List<kechengleixingBean> selectByExample(kechengleixingBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table kechengleixing
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    kechengleixingBean selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table kechengleixing
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int updateByExampleSelective(kechengleixingBean record, kechengleixingBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table kechengleixing
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int updateByExample(kechengleixingBean record, kechengleixingBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table kechengleixing
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int updateByPrimaryKeySelective(kechengleixingBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table kechengleixing
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int updateByPrimaryKey(kechengleixingBean record);
}