package dao;

import bean.kechengleixingBean;
import bean.kechengleixingBeanExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class kechengleixingBeanDAOImpl extends SqlMapClientDaoSupport implements kechengleixingBeanDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table kechengleixing
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public kechengleixingBeanDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table kechengleixing
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public int countByExample(kechengleixingBeanExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("kechengleixing.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table kechengleixing
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public int deleteByExample(kechengleixingBeanExample example) {
        int rows = getSqlMapClientTemplate().delete("kechengleixing.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table kechengleixing
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public int deleteByPrimaryKey(Integer id) {
        kechengleixingBean key = new kechengleixingBean();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("kechengleixing.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table kechengleixing
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void insert(kechengleixingBean record) {
        getSqlMapClientTemplate().insert("kechengleixing.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table kechengleixing
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void insertSelective(kechengleixingBean record) {
        getSqlMapClientTemplate().insert("kechengleixing.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table kechengleixing
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    @SuppressWarnings("unchecked")
    public List<kechengleixingBean> selectByExample(kechengleixingBeanExample example) {
        List<kechengleixingBean> list = getSqlMapClientTemplate().queryForList("kechengleixing.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table kechengleixing
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public kechengleixingBean selectByPrimaryKey(Integer id) {
        kechengleixingBean key = new kechengleixingBean();
        key.setId(id);
        kechengleixingBean record = (kechengleixingBean) getSqlMapClientTemplate().queryForObject("kechengleixing.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table kechengleixing
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public int updateByExampleSelective(kechengleixingBean record, kechengleixingBeanExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("kechengleixing.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table kechengleixing
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public int updateByExample(kechengleixingBean record, kechengleixingBeanExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("kechengleixing.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table kechengleixing
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public int updateByPrimaryKeySelective(kechengleixingBean record) {
        int rows = getSqlMapClientTemplate().update("kechengleixing.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table kechengleixing
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public int updateByPrimaryKey(kechengleixingBean record) {
        int rows = getSqlMapClientTemplate().update("kechengleixing.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table kechengleixing
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private static class UpdateByExampleParms extends kechengleixingBeanExample {
        private Object record;

        public UpdateByExampleParms(Object record, kechengleixingBeanExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}