package dao;

import bean.lanmuguanliBean;
import bean.lanmuguanliBeanExample;
import java.util.List;

public interface lanmuguanliBeanDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table lanmuguanli
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int countByExample(lanmuguanliBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table lanmuguanli
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int deleteByExample(lanmuguanliBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table lanmuguanli
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table lanmuguanli
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    void insert(lanmuguanliBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table lanmuguanli
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    void insertSelective(lanmuguanliBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table lanmuguanli
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    List<lanmuguanliBean> selectByExample(lanmuguanliBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table lanmuguanli
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    lanmuguanliBean selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table lanmuguanli
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int updateByExampleSelective(lanmuguanliBean record, lanmuguanliBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table lanmuguanli
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int updateByExample(lanmuguanliBean record, lanmuguanliBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table lanmuguanli
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int updateByPrimaryKeySelective(lanmuguanliBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table lanmuguanli
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int updateByPrimaryKey(lanmuguanliBean record);
}