package dao;

import bean.luntanhudongBean;
import bean.luntanhudongBeanExample;
import java.util.List;

public interface luntanhudongBeanDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table luntanhudong
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int countByExample(luntanhudongBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table luntanhudong
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int deleteByExample(luntanhudongBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table luntanhudong
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table luntanhudong
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    void insert(luntanhudongBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table luntanhudong
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    void insertSelective(luntanhudongBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table luntanhudong
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    List<luntanhudongBean> selectByExample(luntanhudongBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table luntanhudong
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    luntanhudongBean selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table luntanhudong
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int updateByExampleSelective(luntanhudongBean record, luntanhudongBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table luntanhudong
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int updateByExample(luntanhudongBean record, luntanhudongBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table luntanhudong
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int updateByPrimaryKeySelective(luntanhudongBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table luntanhudong
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int updateByPrimaryKey(luntanhudongBean record);
}