package dao;

import bean.luntanhudongBean;
import bean.luntanhudongBeanExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class luntanhudongBeanDAOImpl extends SqlMapClientDaoSupport implements luntanhudongBeanDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table luntanhudong
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public luntanhudongBeanDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table luntanhudong
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public int countByExample(luntanhudongBeanExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("luntanhudong.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table luntanhudong
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public int deleteByExample(luntanhudongBeanExample example) {
        int rows = getSqlMapClientTemplate().delete("luntanhudong.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table luntanhudong
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public int deleteByPrimaryKey(Integer id) {
        luntanhudongBean key = new luntanhudongBean();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("luntanhudong.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table luntanhudong
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void insert(luntanhudongBean record) {
        getSqlMapClientTemplate().insert("luntanhudong.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table luntanhudong
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void insertSelective(luntanhudongBean record) {
        getSqlMapClientTemplate().insert("luntanhudong.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table luntanhudong
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    @SuppressWarnings("unchecked")
    public List<luntanhudongBean> selectByExample(luntanhudongBeanExample example) {
        List<luntanhudongBean> list = getSqlMapClientTemplate().queryForList("luntanhudong.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table luntanhudong
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public luntanhudongBean selectByPrimaryKey(Integer id) {
        luntanhudongBean key = new luntanhudongBean();
        key.setId(id);
        luntanhudongBean record = (luntanhudongBean) getSqlMapClientTemplate().queryForObject("luntanhudong.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table luntanhudong
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public int updateByExampleSelective(luntanhudongBean record, luntanhudongBeanExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("luntanhudong.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table luntanhudong
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public int updateByExample(luntanhudongBean record, luntanhudongBeanExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("luntanhudong.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table luntanhudong
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public int updateByPrimaryKeySelective(luntanhudongBean record) {
        int rows = getSqlMapClientTemplate().update("luntanhudong.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table luntanhudong
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public int updateByPrimaryKey(luntanhudongBean record) {
        int rows = getSqlMapClientTemplate().update("luntanhudong.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table luntanhudong
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private static class UpdateByExampleParms extends luntanhudongBeanExample {
        private Object record;

        public UpdateByExampleParms(Object record, luntanhudongBeanExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}