package dao;

import bean.paikexinxiBean;
import bean.paikexinxiBeanExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class paikexinxiBeanDAOImpl extends SqlMapClientDaoSupport implements paikexinxiBeanDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table paikexinxi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public paikexinxiBeanDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table paikexinxi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public int countByExample(paikexinxiBeanExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("paikexinxi.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table paikexinxi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public int deleteByExample(paikexinxiBeanExample example) {
        int rows = getSqlMapClientTemplate().delete("paikexinxi.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table paikexinxi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public int deleteByPrimaryKey(Integer id) {
        paikexinxiBean key = new paikexinxiBean();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("paikexinxi.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table paikexinxi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void insert(paikexinxiBean record) {
        getSqlMapClientTemplate().insert("paikexinxi.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table paikexinxi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void insertSelective(paikexinxiBean record) {
        getSqlMapClientTemplate().insert("paikexinxi.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table paikexinxi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    @SuppressWarnings("unchecked")
    public List<paikexinxiBean> selectByExample(paikexinxiBeanExample example) {
        List<paikexinxiBean> list = getSqlMapClientTemplate().queryForList("paikexinxi.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table paikexinxi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public paikexinxiBean selectByPrimaryKey(Integer id) {
        paikexinxiBean key = new paikexinxiBean();
        key.setId(id);
        paikexinxiBean record = (paikexinxiBean) getSqlMapClientTemplate().queryForObject("paikexinxi.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table paikexinxi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public int updateByExampleSelective(paikexinxiBean record, paikexinxiBeanExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("paikexinxi.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table paikexinxi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public int updateByExample(paikexinxiBean record, paikexinxiBeanExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("paikexinxi.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table paikexinxi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public int updateByPrimaryKeySelective(paikexinxiBean record) {
        int rows = getSqlMapClientTemplate().update("paikexinxi.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table paikexinxi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public int updateByPrimaryKey(paikexinxiBean record) {
        int rows = getSqlMapClientTemplate().update("paikexinxi.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table paikexinxi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private static class UpdateByExampleParms extends paikexinxiBeanExample {
        private Object record;

        public UpdateByExampleParms(Object record, paikexinxiBeanExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}