package dao;

import bean.role_menuBean;
import bean.role_menuBeanExample;
import java.util.List;

public interface role_menuBeanDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table role_menu
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int countByExample(role_menuBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table role_menu
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int deleteByExample(role_menuBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table role_menu
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table role_menu
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    void insert(role_menuBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table role_menu
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    void insertSelective(role_menuBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table role_menu
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    List<role_menuBean> selectByExample(role_menuBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table role_menu
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    role_menuBean selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table role_menu
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int updateByExampleSelective(role_menuBean record, role_menuBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table role_menu
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int updateByExample(role_menuBean record, role_menuBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table role_menu
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int updateByPrimaryKeySelective(role_menuBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table role_menu
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int updateByPrimaryKey(role_menuBean record);
}