package dao;

import bean.shoukeshijianduanBean;
import bean.shoukeshijianduanBeanExample;
import java.util.List;

public interface shoukeshijianduanBeanDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table shoukeshijianduan
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int countByExample(shoukeshijianduanBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table shoukeshijianduan
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int deleteByExample(shoukeshijianduanBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table shoukeshijianduan
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table shoukeshijianduan
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    void insert(shoukeshijianduanBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table shoukeshijianduan
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    void insertSelective(shoukeshijianduanBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table shoukeshijianduan
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    List<shoukeshijianduanBean> selectByExample(shoukeshijianduanBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table shoukeshijianduan
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    shoukeshijianduanBean selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table shoukeshijianduan
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int updateByExampleSelective(shoukeshijianduanBean record, shoukeshijianduanBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table shoukeshijianduan
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int updateByExample(shoukeshijianduanBean record, shoukeshijianduanBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table shoukeshijianduan
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int updateByPrimaryKeySelective(shoukeshijianduanBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table shoukeshijianduan
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int updateByPrimaryKey(shoukeshijianduanBean record);
}