package dao;

import bean.shoukeshijianduanBean;
import bean.shoukeshijianduanBeanExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class shoukeshijianduanBeanDAOImpl extends SqlMapClientDaoSupport implements shoukeshijianduanBeanDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table shoukeshijianduan
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public shoukeshijianduanBeanDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table shoukeshijianduan
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public int countByExample(shoukeshijianduanBeanExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("shoukeshijianduan.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table shoukeshijianduan
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public int deleteByExample(shoukeshijianduanBeanExample example) {
        int rows = getSqlMapClientTemplate().delete("shoukeshijianduan.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table shoukeshijianduan
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public int deleteByPrimaryKey(Integer id) {
        shoukeshijianduanBean key = new shoukeshijianduanBean();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("shoukeshijianduan.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table shoukeshijianduan
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void insert(shoukeshijianduanBean record) {
        getSqlMapClientTemplate().insert("shoukeshijianduan.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table shoukeshijianduan
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void insertSelective(shoukeshijianduanBean record) {
        getSqlMapClientTemplate().insert("shoukeshijianduan.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table shoukeshijianduan
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    @SuppressWarnings("unchecked")
    public List<shoukeshijianduanBean> selectByExample(shoukeshijianduanBeanExample example) {
        List<shoukeshijianduanBean> list = getSqlMapClientTemplate().queryForList("shoukeshijianduan.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table shoukeshijianduan
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public shoukeshijianduanBean selectByPrimaryKey(Integer id) {
        shoukeshijianduanBean key = new shoukeshijianduanBean();
        key.setId(id);
        shoukeshijianduanBean record = (shoukeshijianduanBean) getSqlMapClientTemplate().queryForObject("shoukeshijianduan.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table shoukeshijianduan
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public int updateByExampleSelective(shoukeshijianduanBean record, shoukeshijianduanBeanExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("shoukeshijianduan.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table shoukeshijianduan
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public int updateByExample(shoukeshijianduanBean record, shoukeshijianduanBeanExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("shoukeshijianduan.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table shoukeshijianduan
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public int updateByPrimaryKeySelective(shoukeshijianduanBean record) {
        int rows = getSqlMapClientTemplate().update("shoukeshijianduan.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table shoukeshijianduan
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public int updateByPrimaryKey(shoukeshijianduanBean record) {
        int rows = getSqlMapClientTemplate().update("shoukeshijianduan.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table shoukeshijianduan
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private static class UpdateByExampleParms extends shoukeshijianduanBeanExample {
        private Object record;

        public UpdateByExampleParms(Object record, shoukeshijianduanBeanExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}