package dao;

import bean.systemrolemanageBean;
import bean.systemrolemanageBeanExample;
import java.util.List;

public interface systemrolemanageBeanDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table systemrolemanage
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int countByExample(systemrolemanageBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table systemrolemanage
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int deleteByExample(systemrolemanageBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table systemrolemanage
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table systemrolemanage
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    void insert(systemrolemanageBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table systemrolemanage
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    void insertSelective(systemrolemanageBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table systemrolemanage
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    List<systemrolemanageBean> selectByExample(systemrolemanageBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table systemrolemanage
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    systemrolemanageBean selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table systemrolemanage
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int updateByExampleSelective(systemrolemanageBean record, systemrolemanageBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table systemrolemanage
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int updateByExample(systemrolemanageBean record, systemrolemanageBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table systemrolemanage
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int updateByPrimaryKeySelective(systemrolemanageBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table systemrolemanage
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int updateByPrimaryKey(systemrolemanageBean record);
}