package dao;

import bean.table_picBean;
import bean.table_picBeanExample;
import java.util.List;

public interface table_picBeanDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table table_pic
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int countByExample(table_picBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table table_pic
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int deleteByExample(table_picBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table table_pic
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table table_pic
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    void insert(table_picBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table table_pic
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    void insertSelective(table_picBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table table_pic
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    List<table_picBean> selectByExample(table_picBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table table_pic
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    table_picBean selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table table_pic
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int updateByExampleSelective(table_picBean record, table_picBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table table_pic
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int updateByExample(table_picBean record, table_picBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table table_pic
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int updateByPrimaryKeySelective(table_picBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table table_pic
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int updateByPrimaryKey(table_picBean record);
}