package dao;

import bean.user_menuBean;
import bean.user_menuBeanExample;
import java.util.List;

public interface user_menuBeanDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_menu
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int countByExample(user_menuBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_menu
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int deleteByExample(user_menuBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_menu
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_menu
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    void insert(user_menuBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_menu
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    void insertSelective(user_menuBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_menu
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    List<user_menuBean> selectByExample(user_menuBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_menu
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    user_menuBean selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_menu
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int updateByExampleSelective(user_menuBean record, user_menuBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_menu
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int updateByExample(user_menuBean record, user_menuBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_menu
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int updateByPrimaryKeySelective(user_menuBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_menu
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int updateByPrimaryKey(user_menuBean record);
}