package dao;

import bean.xiaofeiqiandaoBean;
import bean.xiaofeiqiandaoBeanExample;
import java.util.List;

public interface xiaofeiqiandaoBeanDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xiaofeiqiandao
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int countByExample(xiaofeiqiandaoBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xiaofeiqiandao
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int deleteByExample(xiaofeiqiandaoBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xiaofeiqiandao
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xiaofeiqiandao
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    void insert(xiaofeiqiandaoBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xiaofeiqiandao
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    void insertSelective(xiaofeiqiandaoBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xiaofeiqiandao
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    List<xiaofeiqiandaoBean> selectByExample(xiaofeiqiandaoBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xiaofeiqiandao
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    xiaofeiqiandaoBean selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xiaofeiqiandao
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int updateByExampleSelective(xiaofeiqiandaoBean record, xiaofeiqiandaoBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xiaofeiqiandao
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int updateByExample(xiaofeiqiandaoBean record, xiaofeiqiandaoBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xiaofeiqiandao
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int updateByPrimaryKeySelective(xiaofeiqiandaoBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xiaofeiqiandao
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int updateByPrimaryKey(xiaofeiqiandaoBean record);
}