package dao;

import bean.zhifufangshiBean;
import bean.zhifufangshiBeanExample;
import java.util.List;

public interface zhifufangshiBeanDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table zhifufangshi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int countByExample(zhifufangshiBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table zhifufangshi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int deleteByExample(zhifufangshiBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table zhifufangshi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table zhifufangshi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    void insert(zhifufangshiBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table zhifufangshi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    void insertSelective(zhifufangshiBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table zhifufangshi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    List<zhifufangshiBean> selectByExample(zhifufangshiBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table zhifufangshi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    zhifufangshiBean selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table zhifufangshi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int updateByExampleSelective(zhifufangshiBean record, zhifufangshiBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table zhifufangshi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int updateByExample(zhifufangshiBean record, zhifufangshiBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table zhifufangshi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int updateByPrimaryKeySelective(zhifufangshiBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table zhifufangshi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    int updateByPrimaryKey(zhifufangshiBean record);
}