package dao;

import bean.zhifufangshiBean;
import bean.zhifufangshiBeanExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class zhifufangshiBeanDAOImpl extends SqlMapClientDaoSupport implements zhifufangshiBeanDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table zhifufangshi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public zhifufangshiBeanDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table zhifufangshi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public int countByExample(zhifufangshiBeanExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("zhifufangshi.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table zhifufangshi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public int deleteByExample(zhifufangshiBeanExample example) {
        int rows = getSqlMapClientTemplate().delete("zhifufangshi.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table zhifufangshi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public int deleteByPrimaryKey(Integer id) {
        zhifufangshiBean key = new zhifufangshiBean();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("zhifufangshi.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table zhifufangshi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void insert(zhifufangshiBean record) {
        getSqlMapClientTemplate().insert("zhifufangshi.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table zhifufangshi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void insertSelective(zhifufangshiBean record) {
        getSqlMapClientTemplate().insert("zhifufangshi.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table zhifufangshi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    @SuppressWarnings("unchecked")
    public List<zhifufangshiBean> selectByExample(zhifufangshiBeanExample example) {
        List<zhifufangshiBean> list = getSqlMapClientTemplate().queryForList("zhifufangshi.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table zhifufangshi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public zhifufangshiBean selectByPrimaryKey(Integer id) {
        zhifufangshiBean key = new zhifufangshiBean();
        key.setId(id);
        zhifufangshiBean record = (zhifufangshiBean) getSqlMapClientTemplate().queryForObject("zhifufangshi.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table zhifufangshi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public int updateByExampleSelective(zhifufangshiBean record, zhifufangshiBeanExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("zhifufangshi.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table zhifufangshi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public int updateByExample(zhifufangshiBean record, zhifufangshiBeanExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("zhifufangshi.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table zhifufangshi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public int updateByPrimaryKeySelective(zhifufangshiBean record) {
        int rows = getSqlMapClientTemplate().update("zhifufangshi.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table zhifufangshi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public int updateByPrimaryKey(zhifufangshiBean record) {
        int rows = getSqlMapClientTemplate().update("zhifufangshi.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table zhifufangshi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private static class UpdateByExampleParms extends zhifufangshiBeanExample {
        private Object record;

        public UpdateByExampleParms(Object record, zhifufangshiBeanExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}