// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Aside: typeof import('./src/components/content/Aside/index.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Header: typeof import('./src/components/content/Header/index.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IAntDesignArrowsAltOutlined: typeof import('~icons/ant-design/arrows-alt-outlined')['default']
    IAntDesignCloseOutlined: typeof import('~icons/ant-design/close-outlined')['default']
    IAntDesignHeartOutlined: typeof import('~icons/ant-design/heart-outlined')['default']
    IAntDesignLineOutlined: typeof import('~icons/ant-design/line-outlined')['default']
    IAntDesignShrinkOutlined: typeof import('~icons/ant-design/shrink-outlined')['default']
    IIcRoundDownload: typeof import('~icons/ic/round-download')['default']
    IIcRoundDownloadDone: typeof import('~icons/ic/round-download-done')['default']
    IIcRoundFavorite: typeof import('~icons/ic/round-favorite')['default']
    IIcRoundFavoriteBorder: typeof import('~icons/ic/round-favorite-border')['default']
    IIcRoundFavoriteOutline: typeof import('~icons/ic/round-favorite-outline')['default']
    IIcRoundFormatListBulleted: typeof import('~icons/ic/round-format-list-bulleted')['default']
    IIcRoundFullscreen: typeof import('~icons/ic/round-fullscreen')['default']
    IIcRoundFullscreenExit: typeof import('~icons/ic/round-fullscreen-exit')['default']
    IIcRoundPause: typeof import('~icons/ic/round-pause')['default']
    IIcRoundPlayArrow: typeof import('~icons/ic/round-play-arrow')['default']
    IIcRoundRepeat: typeof import('~icons/ic/round-repeat')['default']
    IIcRoundRepeatOne: typeof import('~icons/ic/round-repeat-one')['default']
    IIcRoundSkipNext: typeof import('~icons/ic/round-skip-next')['default']
    IIcRoundSkipPrevious: typeof import('~icons/ic/round-skip-previous')['default']
    IIcRoundVolumeOff: typeof import('~icons/ic/round-volume-off')['default']
    IIcRoundVolumeUp: typeof import('~icons/ic/round-volume-up')['default']
    ILaRandom: typeof import('~icons/la/random')['default']
    Menu: typeof import('./src/components/content/Menu/index.vue')['default']
    MusicBar: typeof import('./src/components/content/MusicBar/index.vue')['default']
    MusicDetail: typeof import('./src/components/content/MusicDetail/index.vue')['default']
    MusicLyric: typeof import('./src/components/content/MusicDetail/components/MusicLyric/index.vue')['default']
    MusicPic: typeof import('./src/components/content/MusicDetail/components/MusicPic/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
