# 数据库连接配置
spring:
  profiles:
    active: dev
  datasource:
    #    url: jdbc:mysql://remotemysql.com:3306/umHddtxzhZ?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8

    url: jdbc:mysql://192.168.61.130:3306/box-music?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 111111
    #    username: umHddtxzhZ
    #    password: cILmJJ31Z6
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 120MB
      max-request-size: 120MB

  # mybatis plus 逻辑删除配置
  global-config:
    db-config:
      logic-delete-field: deleted  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

  #  redis:
  #    host: 192.168.61.131
  #    # 默认可以不写
  #    port: 6379
  #    database: 0
  #    password: 111111
  #    redis2:
  #      host: 192.168.61.131
  #      port: 6379
  #      database: 1
  #      password: 111111

  #  redis:
  #    host: redis-12411.c9.us-east-1-4.ec2.cloud.redislabs.com
  #    port: 12411
  #    database: 0
  #    password: 18558612103

#  redis:
#    host: 106.14.145.147
#    port: 33333
#    database: 0
#    password: 123456

  redis:
    host: 192.168.61.130
    port: 6379
    database: 0
#    password: 111111

# 开启 mybatis plus 缓存 不加也可以
mybatis-plus:
  configuration:
    cache-enabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    
uid:
  timeBits: 30             # 时间位, 默认:30
  workerBits: 16           # 机器位, 默认:16
  seqBits: 7               # 序列号, 默认:7
  epochStr: "2022-01-01"   # 初始时间, 默认:"2019-02-20"
  enableBackward: true    # 是否容忍时钟回拨, 默认:true
  maxBackwardSeconds: 1    # 时钟回拨最长容忍时间（秒）, 默认:1
  CachedUidGenerator:     # CachedUidGenerator相关参数
    boostPower: 3          # RingBuffer size扩容参数, 可提高UID生成的吞吐量, 默认:3
    paddingFactor: 50      # 指定何时向RingBuffer中填充UID, 取值为百分比(0, 100), 默认为50
    #scheduleInterval: 60    # 默认:不配置此项, 即不使用Schedule线程. 如需使用, 请指定Schedule线程时间间隔, 单位:秒
    
userPicturePathRelative: /user-pictures/**
userPicturePath: G:/box-music/user-pictures/

albumPicturePathRelative: /album-pictures/**
albumPicturePath: G:/box-music/album-pictures/

singerPicturePathRelative: /singer-pictures/**
singerPicturePath: G:/box-music/singer-pictures/

categoryPicturePathRelative: /category-pictures/**
categoryPicturePath: G:/box-music/category-pictures/

playlistPicturePathRelative: /playlist-pictures/**
playlistPicturePath: G:/box-music/playlist-pictures/

musicPathRelative: /musics/**
musicPath: G:/box-music/musics/

otherUploadPathRelative: /others/**
otherUploadPath: G:/Files/Others/

spiderPathRelative: /spider/**
#spiderPath: G:/box_music/
spiderPath: G:/box-music/

tempPath: G:/box-music/temp/
