export enum MessageType {
	WINDOW_SCREEN = 'window-screen',
	WINDOW_FULLSCREEN = 'window-fullscreen',
	WINDOW_FULLSCREEN_EXIT = 'window-fullscreen-exit',
	WINDOW_MIN = 'window-min',
	WINDOW_MAX = 'window-max',
	WINDOW_CHANGE = 'window-change',
	WINDOW_CLOSE = 'window-close',
	DOWNLOAD_START = 'download-start',
	DOWNLOAD_PAUSE = 'download-pause',
	DOWNLOAD_RESUME = 'download-resume',
	DOWNLOAD_CANCEL = 'download-cancel',
	DOWNLOAD_FINISH = 'download-finish',
	DOWNLOAD_UPDATE = 'download-update',
	DOWNLOAD_RESTART = 'download-restart',
	DOWNLOAD_EXIT = 'download-exit',
	DOWNLOAD_EXIT_FORCE = 'download-exit-force',
	WILL_DOWNLOAD = 'will-download',
	WRITEIN_UPDATE = 'writein-update',
	WRITEIN_FINISH = 'writein-finish',
	OPEN_DIR = 'open-dir'
}
