server:
  port: 8989

spring:
  application:
    name: gateway
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
    gateway:
      routes:
        - id: user_route
#          uri: http://localhost:9999/
          uri: lb://users # lb：使用负载均衡策略  users代表注册中心的具体服务名
          predicates:
            - Path=/user/**,/feign/**

        - id: product_route
#          uri: http://localhost:9998/
          uri: lb://products # lb：使用负载均衡策略  products代表注册中心的具体服务名
          predicates:
            - Path=/product/**
#            - After=2021-02-18T16:52:36.404+08:00[Asia/Shanghai] # 在这个时间之后才能访问到
#            - Before=2021-02-18T16:48:36.404+08:00[Asia/Shanghai] # 在这个时间之前生效
#            - Between=2021-02-18T16:48:36.404+08:00[Asia/Shanghai], 2021-02-18T16:48:36.404+08:00[Asia/Shanghai] # 在这个时间段内生效
#            - Cookie=chocolate, ch.p # 表示这个cookie必须key是chocolate，value是ch.p可以访问
#            - Cookie=username,[A-Za-z0-9]+ # 基于正则表达式
#            - Header=X-Request-Id,\d+ # 基于请求头方式进行请求
#            - Method=GET,POST # 基于请求方式
#          filters: # 经过上面断言后经过过滤器
#            - AddRequestParameter=id,34 # 给请求头加上参数id，值为34
#            - AddResponseHeader=X-Response-Red,Red # 给相应头添加X-Response-Red,Red

      discovery:
        locator:
          enabled: true # 开启根据动态服务名动态获取路由地址
management:
  endpoints:
    web:
      exposure:
        include: "*"  # 暴露所有的路由端点