spring:
  datasource:
    url: jdbc:mysql:///user_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 111111
    driver-class-name: com.mysql.cj.jdbc.Driver

#mybatis-plus:
#  type-aliases-package: com.example.mp.entity
#mybatis-plus:
#  mapper-locations: classpath*:/mapper/xml/*.xml
#  mapper-locations: classpath*:com/example/mp/mapper/xml/*.xml
