server:
  port: 8081

spring:

  datasource:
    url: jdbc:mysql:///jwt?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 111111
    driver-class-name: com.mysql.cj.jdbc.Driver
