package bean;

public class kechengleixingBean {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column kechengleixing.id
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column kechengleixing.kechengleixing
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String kechengleixing;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column kechengleixing.operatorId
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String operatorid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column kechengleixing.itime
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String itime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column kechengleixing.detail
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String detail;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column kechengleixing.deleteFlag
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private Integer deleteflag;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column kechengleixing.erjiguanlianzd
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String erjiguanlianzd;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column kechengleixing.id
     *
     * @return the value of kechengleixing.id
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column kechengleixing.id
     *
     * @param id the value for kechengleixing.id
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column kechengleixing.kechengleixing
     *
     * @return the value of kechengleixing.kechengleixing
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getKechengleixing() {
        return kechengleixing;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column kechengleixing.kechengleixing
     *
     * @param kechengleixing the value for kechengleixing.kechengleixing
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setKechengleixing(String kechengleixing) {
        this.kechengleixing = kechengleixing;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column kechengleixing.operatorId
     *
     * @return the value of kechengleixing.operatorId
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getOperatorid() {
        return operatorid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column kechengleixing.operatorId
     *
     * @param operatorid the value for kechengleixing.operatorId
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setOperatorid(String operatorid) {
        this.operatorid = operatorid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column kechengleixing.itime
     *
     * @return the value of kechengleixing.itime
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getItime() {
        return itime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column kechengleixing.itime
     *
     * @param itime the value for kechengleixing.itime
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setItime(String itime) {
        this.itime = itime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column kechengleixing.detail
     *
     * @return the value of kechengleixing.detail
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column kechengleixing.detail
     *
     * @param detail the value for kechengleixing.detail
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setDetail(String detail) {
        this.detail = detail;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column kechengleixing.deleteFlag
     *
     * @return the value of kechengleixing.deleteFlag
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public Integer getDeleteflag() {
        return deleteflag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column kechengleixing.deleteFlag
     *
     * @param deleteflag the value for kechengleixing.deleteFlag
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setDeleteflag(Integer deleteflag) {
        this.deleteflag = deleteflag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column kechengleixing.erjiguanlianzd
     *
     * @return the value of kechengleixing.erjiguanlianzd
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getErjiguanlianzd() {
        return erjiguanlianzd;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column kechengleixing.erjiguanlianzd
     *
     * @param erjiguanlianzd the value for kechengleixing.erjiguanlianzd
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setErjiguanlianzd(String erjiguanlianzd) {
        this.erjiguanlianzd = erjiguanlianzd;
    }
}