package bean;

public class luntanhudongBean {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column luntanhudong.id
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column luntanhudong.fabiaotimu
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String fabiaotimu;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column luntanhudong.fabiaoneirong
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String fabiaoneirong;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column luntanhudong.faburen
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String faburen;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column luntanhudong.fabushijian
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String fabushijian;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column luntanhudong.fuJian
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String fujian;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column luntanhudong.operatorId
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String operatorid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column luntanhudong.itime
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String itime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column luntanhudong.detail
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String detail;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column luntanhudong.deleteFlag
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private Integer deleteflag;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column luntanhudong.erjiguanlianzd
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String erjiguanlianzd;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column luntanhudong.id
     *
     * @return the value of luntanhudong.id
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column luntanhudong.id
     *
     * @param id the value for luntanhudong.id
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column luntanhudong.fabiaotimu
     *
     * @return the value of luntanhudong.fabiaotimu
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getFabiaotimu() {
        return fabiaotimu;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column luntanhudong.fabiaotimu
     *
     * @param fabiaotimu the value for luntanhudong.fabiaotimu
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setFabiaotimu(String fabiaotimu) {
        this.fabiaotimu = fabiaotimu;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column luntanhudong.fabiaoneirong
     *
     * @return the value of luntanhudong.fabiaoneirong
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getfabiaoneirong() {
        return fabiaoneirong;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column luntanhudong.fabiaoneirong
     *
     * @param fabiaoneirong the value for luntanhudong.fabiaoneirong
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setfabiaoneirong(String fabiaoneirong) {
        this.fabiaoneirong = fabiaoneirong;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column luntanhudong.faburen
     *
     * @return the value of luntanhudong.faburen
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getFaburen() {
        return faburen;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column luntanhudong.faburen
     *
     * @param faburen the value for luntanhudong.faburen
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setFaburen(String faburen) {
        this.faburen = faburen;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column luntanhudong.fabushijian
     *
     * @return the value of luntanhudong.fabushijian
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getFabushijian() {
        return fabushijian;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column luntanhudong.fabushijian
     *
     * @param fabushijian the value for luntanhudong.fabushijian
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setFabushijian(String fabushijian) {
        this.fabushijian = fabushijian;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column luntanhudong.fuJian
     *
     * @return the value of luntanhudong.fuJian
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getFujian() {
        return fujian;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column luntanhudong.fuJian
     *
     * @param fujian the value for luntanhudong.fuJian
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setFujian(String fujian) {
        this.fujian = fujian;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column luntanhudong.operatorId
     *
     * @return the value of luntanhudong.operatorId
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getOperatorid() {
        return operatorid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column luntanhudong.operatorId
     *
     * @param operatorid the value for luntanhudong.operatorId
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setOperatorid(String operatorid) {
        this.operatorid = operatorid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column luntanhudong.itime
     *
     * @return the value of luntanhudong.itime
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getItime() {
        return itime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column luntanhudong.itime
     *
     * @param itime the value for luntanhudong.itime
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setItime(String itime) {
        this.itime = itime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column luntanhudong.detail
     *
     * @return the value of luntanhudong.detail
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column luntanhudong.detail
     *
     * @param detail the value for luntanhudong.detail
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setDetail(String detail) {
        this.detail = detail;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column luntanhudong.deleteFlag
     *
     * @return the value of luntanhudong.deleteFlag
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public Integer getDeleteflag() {
        return deleteflag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column luntanhudong.deleteFlag
     *
     * @param deleteflag the value for luntanhudong.deleteFlag
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setDeleteflag(Integer deleteflag) {
        this.deleteflag = deleteflag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column luntanhudong.erjiguanlianzd
     *
     * @return the value of luntanhudong.erjiguanlianzd
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getErjiguanlianzd() {
        return erjiguanlianzd;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column luntanhudong.erjiguanlianzd
     *
     * @param erjiguanlianzd the value for luntanhudong.erjiguanlianzd
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setErjiguanlianzd(String erjiguanlianzd) {
        this.erjiguanlianzd = erjiguanlianzd;
    }
}