package bean;

public class menu_infoBean {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column menu_info.id
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column menu_info.menu_name
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String menuName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column menu_info.menu_ename
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String menuEname;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column menu_info.f_id
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private Integer fId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column menu_info.menu_todo
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String menuTodo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column menu_info.menu_status
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private Integer menuStatus;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column menu_info.menu_type
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private Integer menuType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column menu_info.menu_index
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private Integer menuIndex;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column menu_info.menu_table
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String menuTable;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column menu_info.view_menu
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private Integer viewMenu;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column menu_info.detail
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String detail;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column menu_info.data_right
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private Integer dataRight;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column menu_info.exDataRight
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String exdataright;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column menu_info.export_excel
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private Integer exportExcel;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column menu_info.fuJian
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private Integer fujian;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column menu_info.frontS
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private Integer fronts;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column menu_info.shenpi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private Integer shenpi;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column menu_info.is_default
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private Integer isDefault;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column menu_info.tuPian
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private Integer tupian;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column menu_info.isErJi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private Integer iserji;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column menu_info.erJiUrl
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String erjiurl;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column menu_info.id
     *
     * @return the value of menu_info.id
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column menu_info.id
     *
     * @param id the value for menu_info.id
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column menu_info.menu_name
     *
     * @return the value of menu_info.menu_name
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column menu_info.menu_name
     *
     * @param menuName the value for menu_info.menu_name
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column menu_info.menu_ename
     *
     * @return the value of menu_info.menu_ename
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getMenuEname() {
        return menuEname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column menu_info.menu_ename
     *
     * @param menuEname the value for menu_info.menu_ename
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setMenuEname(String menuEname) {
        this.menuEname = menuEname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column menu_info.f_id
     *
     * @return the value of menu_info.f_id
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public Integer getfId() {
        return fId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column menu_info.f_id
     *
     * @param fId the value for menu_info.f_id
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setfId(Integer fId) {
        this.fId = fId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column menu_info.menu_todo
     *
     * @return the value of menu_info.menu_todo
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getMenuTodo() {
        return menuTodo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column menu_info.menu_todo
     *
     * @param menuTodo the value for menu_info.menu_todo
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setMenuTodo(String menuTodo) {
        this.menuTodo = menuTodo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column menu_info.menu_status
     *
     * @return the value of menu_info.menu_status
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public Integer getMenuStatus() {
        return menuStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column menu_info.menu_status
     *
     * @param menuStatus the value for menu_info.menu_status
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setMenuStatus(Integer menuStatus) {
        this.menuStatus = menuStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column menu_info.menu_type
     *
     * @return the value of menu_info.menu_type
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public Integer getMenuType() {
        return menuType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column menu_info.menu_type
     *
     * @param menuType the value for menu_info.menu_type
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setMenuType(Integer menuType) {
        this.menuType = menuType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column menu_info.menu_index
     *
     * @return the value of menu_info.menu_index
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public Integer getMenuIndex() {
        return menuIndex;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column menu_info.menu_index
     *
     * @param menuIndex the value for menu_info.menu_index
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setMenuIndex(Integer menuIndex) {
        this.menuIndex = menuIndex;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column menu_info.menu_table
     *
     * @return the value of menu_info.menu_table
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getMenuTable() {
        return menuTable;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column menu_info.menu_table
     *
     * @param menuTable the value for menu_info.menu_table
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setMenuTable(String menuTable) {
        this.menuTable = menuTable;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column menu_info.view_menu
     *
     * @return the value of menu_info.view_menu
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public Integer getViewMenu() {
        return viewMenu;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column menu_info.view_menu
     *
     * @param viewMenu the value for menu_info.view_menu
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setViewMenu(Integer viewMenu) {
        this.viewMenu = viewMenu;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column menu_info.detail
     *
     * @return the value of menu_info.detail
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column menu_info.detail
     *
     * @param detail the value for menu_info.detail
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setDetail(String detail) {
        this.detail = detail;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column menu_info.data_right
     *
     * @return the value of menu_info.data_right
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public Integer getDataRight() {
        return dataRight;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column menu_info.data_right
     *
     * @param dataRight the value for menu_info.data_right
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setDataRight(Integer dataRight) {
        this.dataRight = dataRight;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column menu_info.exDataRight
     *
     * @return the value of menu_info.exDataRight
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getExdataright() {
        return exdataright;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column menu_info.exDataRight
     *
     * @param exdataright the value for menu_info.exDataRight
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setExdataright(String exdataright) {
        this.exdataright = exdataright;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column menu_info.export_excel
     *
     * @return the value of menu_info.export_excel
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public Integer getExportExcel() {
        return exportExcel;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column menu_info.export_excel
     *
     * @param exportExcel the value for menu_info.export_excel
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setExportExcel(Integer exportExcel) {
        this.exportExcel = exportExcel;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column menu_info.fuJian
     *
     * @return the value of menu_info.fuJian
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public Integer getFujian() {
        return fujian;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column menu_info.fuJian
     *
     * @param fujian the value for menu_info.fuJian
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setFujian(Integer fujian) {
        this.fujian = fujian;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column menu_info.frontS
     *
     * @return the value of menu_info.frontS
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public Integer getFronts() {
        return fronts;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column menu_info.frontS
     *
     * @param fronts the value for menu_info.frontS
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setFronts(Integer fronts) {
        this.fronts = fronts;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column menu_info.shenpi
     *
     * @return the value of menu_info.shenpi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public Integer getShenpi() {
        return shenpi;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column menu_info.shenpi
     *
     * @param shenpi the value for menu_info.shenpi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setShenpi(Integer shenpi) {
        this.shenpi = shenpi;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column menu_info.is_default
     *
     * @return the value of menu_info.is_default
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public Integer getIsDefault() {
        return isDefault;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column menu_info.is_default
     *
     * @param isDefault the value for menu_info.is_default
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setIsDefault(Integer isDefault) {
        this.isDefault = isDefault;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column menu_info.tuPian
     *
     * @return the value of menu_info.tuPian
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public Integer getTupian() {
        return tupian;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column menu_info.tuPian
     *
     * @param tupian the value for menu_info.tuPian
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setTupian(Integer tupian) {
        this.tupian = tupian;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column menu_info.isErJi
     *
     * @return the value of menu_info.isErJi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public Integer getIserji() {
        return iserji;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column menu_info.isErJi
     *
     * @param iserji the value for menu_info.isErJi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setIserji(Integer iserji) {
        this.iserji = iserji;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column menu_info.erJiUrl
     *
     * @return the value of menu_info.erJiUrl
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getErjiurl() {
        return erjiurl;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column menu_info.erJiUrl
     *
     * @param erjiurl the value for menu_info.erJiUrl
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setErjiurl(String erjiurl) {
        this.erjiurl = erjiurl;
    }
}