package bean;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class paikexinxiBeanExample {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table paikexinxi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table paikexinxi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table paikexinxi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public paikexinxiBeanExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table paikexinxi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    protected paikexinxiBeanExample(paikexinxiBeanExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table paikexinxi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table paikexinxi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table paikexinxi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table paikexinxi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table paikexinxi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table paikexinxi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table paikexinxi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table paikexinxi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public static class Criteria {
        protected List<String> criteriaWithoutValue;

        protected List<Map<String, Object>> criteriaWithSingleValue;

        protected List<Map<String, Object>> criteriaWithListValue;

        protected List<Map<String, Object>> criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList<String>();
            criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
            criteriaWithListValue = new ArrayList<Map<String, Object>>();
            criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List<String> getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List<Map<String, Object>> getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List<Map<String, Object>> getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List<Map<String, Object>> getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List<? extends Object> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List<Object> list = new ArrayList<Object>();
            list.add(value1);
            list.add(value2);
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return this;
        }

        public Criteria andJiaolianmingchenIsNull() {
            addCriterion("jiaolianmingchen is null");
            return this;
        }

        public Criteria andJiaolianmingchenIsNotNull() {
            addCriterion("jiaolianmingchen is not null");
            return this;
        }

        public Criteria andJiaolianmingchenEqualTo(String value) {
            addCriterion("jiaolianmingchen =", value, "jiaolianmingchen");
            return this;
        }

        public Criteria andJiaolianmingchenNotEqualTo(String value) {
            addCriterion("jiaolianmingchen <>", value, "jiaolianmingchen");
            return this;
        }

        public Criteria andJiaolianmingchenGreaterThan(String value) {
            addCriterion("jiaolianmingchen >", value, "jiaolianmingchen");
            return this;
        }

        public Criteria andJiaolianmingchenGreaterThanOrEqualTo(String value) {
            addCriterion("jiaolianmingchen >=", value, "jiaolianmingchen");
            return this;
        }

        public Criteria andJiaolianmingchenLessThan(String value) {
            addCriterion("jiaolianmingchen <", value, "jiaolianmingchen");
            return this;
        }

        public Criteria andJiaolianmingchenLessThanOrEqualTo(String value) {
            addCriterion("jiaolianmingchen <=", value, "jiaolianmingchen");
            return this;
        }

        public Criteria andJiaolianmingchenLike(String value) {
            addCriterion("jiaolianmingchen like", value, "jiaolianmingchen");
            return this;
        }

        public Criteria andJiaolianmingchenNotLike(String value) {
            addCriterion("jiaolianmingchen not like", value, "jiaolianmingchen");
            return this;
        }

        public Criteria andJiaolianmingchenIn(List<String> values) {
            addCriterion("jiaolianmingchen in", values, "jiaolianmingchen");
            return this;
        }

        public Criteria andJiaolianmingchenNotIn(List<String> values) {
            addCriterion("jiaolianmingchen not in", values, "jiaolianmingchen");
            return this;
        }

        public Criteria andJiaolianmingchenBetween(String value1, String value2) {
            addCriterion("jiaolianmingchen between", value1, value2, "jiaolianmingchen");
            return this;
        }

        public Criteria andJiaolianmingchenNotBetween(String value1, String value2) {
            addCriterion("jiaolianmingchen not between", value1, value2, "jiaolianmingchen");
            return this;
        }

        public Criteria andJiaoliandengjiIsNull() {
            addCriterion("jiaoliandengji is null");
            return this;
        }

        public Criteria andJiaoliandengjiIsNotNull() {
            addCriterion("jiaoliandengji is not null");
            return this;
        }

        public Criteria andJiaoliandengjiEqualTo(String value) {
            addCriterion("jiaoliandengji =", value, "jiaoliandengji");
            return this;
        }

        public Criteria andJiaoliandengjiNotEqualTo(String value) {
            addCriterion("jiaoliandengji <>", value, "jiaoliandengji");
            return this;
        }

        public Criteria andJiaoliandengjiGreaterThan(String value) {
            addCriterion("jiaoliandengji >", value, "jiaoliandengji");
            return this;
        }

        public Criteria andJiaoliandengjiGreaterThanOrEqualTo(String value) {
            addCriterion("jiaoliandengji >=", value, "jiaoliandengji");
            return this;
        }

        public Criteria andJiaoliandengjiLessThan(String value) {
            addCriterion("jiaoliandengji <", value, "jiaoliandengji");
            return this;
        }

        public Criteria andJiaoliandengjiLessThanOrEqualTo(String value) {
            addCriterion("jiaoliandengji <=", value, "jiaoliandengji");
            return this;
        }

        public Criteria andJiaoliandengjiLike(String value) {
            addCriterion("jiaoliandengji like", value, "jiaoliandengji");
            return this;
        }

        public Criteria andJiaoliandengjiNotLike(String value) {
            addCriterion("jiaoliandengji not like", value, "jiaoliandengji");
            return this;
        }

        public Criteria andJiaoliandengjiIn(List<String> values) {
            addCriterion("jiaoliandengji in", values, "jiaoliandengji");
            return this;
        }

        public Criteria andJiaoliandengjiNotIn(List<String> values) {
            addCriterion("jiaoliandengji not in", values, "jiaoliandengji");
            return this;
        }

        public Criteria andJiaoliandengjiBetween(String value1, String value2) {
            addCriterion("jiaoliandengji between", value1, value2, "jiaoliandengji");
            return this;
        }

        public Criteria andJiaoliandengjiNotBetween(String value1, String value2) {
            addCriterion("jiaoliandengji not between", value1, value2, "jiaoliandengji");
            return this;
        }

        public Criteria andShoukemingchenIsNull() {
            addCriterion("shoukemingchen is null");
            return this;
        }

        public Criteria andShoukemingchenIsNotNull() {
            addCriterion("shoukemingchen is not null");
            return this;
        }

        public Criteria andShoukemingchenEqualTo(String value) {
            addCriterion("shoukemingchen =", value, "shoukemingchen");
            return this;
        }

        public Criteria andShoukemingchenNotEqualTo(String value) {
            addCriterion("shoukemingchen <>", value, "shoukemingchen");
            return this;
        }

        public Criteria andShoukemingchenGreaterThan(String value) {
            addCriterion("shoukemingchen >", value, "shoukemingchen");
            return this;
        }

        public Criteria andShoukemingchenGreaterThanOrEqualTo(String value) {
            addCriterion("shoukemingchen >=", value, "shoukemingchen");
            return this;
        }

        public Criteria andShoukemingchenLessThan(String value) {
            addCriterion("shoukemingchen <", value, "shoukemingchen");
            return this;
        }

        public Criteria andShoukemingchenLessThanOrEqualTo(String value) {
            addCriterion("shoukemingchen <=", value, "shoukemingchen");
            return this;
        }

        public Criteria andShoukemingchenLike(String value) {
            addCriterion("shoukemingchen like", value, "shoukemingchen");
            return this;
        }

        public Criteria andShoukemingchenNotLike(String value) {
            addCriterion("shoukemingchen not like", value, "shoukemingchen");
            return this;
        }

        public Criteria andShoukemingchenIn(List<String> values) {
            addCriterion("shoukemingchen in", values, "shoukemingchen");
            return this;
        }

        public Criteria andShoukemingchenNotIn(List<String> values) {
            addCriterion("shoukemingchen not in", values, "shoukemingchen");
            return this;
        }

        public Criteria andShoukemingchenBetween(String value1, String value2) {
            addCriterion("shoukemingchen between", value1, value2, "shoukemingchen");
            return this;
        }

        public Criteria andShoukemingchenNotBetween(String value1, String value2) {
            addCriterion("shoukemingchen not between", value1, value2, "shoukemingchen");
            return this;
        }

        public Criteria andKechengleixingIsNull() {
            addCriterion("kechengleixing is null");
            return this;
        }

        public Criteria andKechengleixingIsNotNull() {
            addCriterion("kechengleixing is not null");
            return this;
        }

        public Criteria andKechengleixingEqualTo(String value) {
            addCriterion("kechengleixing =", value, "kechengleixing");
            return this;
        }

        public Criteria andKechengleixingNotEqualTo(String value) {
            addCriterion("kechengleixing <>", value, "kechengleixing");
            return this;
        }

        public Criteria andKechengleixingGreaterThan(String value) {
            addCriterion("kechengleixing >", value, "kechengleixing");
            return this;
        }

        public Criteria andKechengleixingGreaterThanOrEqualTo(String value) {
            addCriterion("kechengleixing >=", value, "kechengleixing");
            return this;
        }

        public Criteria andKechengleixingLessThan(String value) {
            addCriterion("kechengleixing <", value, "kechengleixing");
            return this;
        }

        public Criteria andKechengleixingLessThanOrEqualTo(String value) {
            addCriterion("kechengleixing <=", value, "kechengleixing");
            return this;
        }

        public Criteria andKechengleixingLike(String value) {
            addCriterion("kechengleixing like", value, "kechengleixing");
            return this;
        }

        public Criteria andKechengleixingNotLike(String value) {
            addCriterion("kechengleixing not like", value, "kechengleixing");
            return this;
        }

        public Criteria andKechengleixingIn(List<String> values) {
            addCriterion("kechengleixing in", values, "kechengleixing");
            return this;
        }

        public Criteria andKechengleixingNotIn(List<String> values) {
            addCriterion("kechengleixing not in", values, "kechengleixing");
            return this;
        }

        public Criteria andKechengleixingBetween(String value1, String value2) {
            addCriterion("kechengleixing between", value1, value2, "kechengleixing");
            return this;
        }

        public Criteria andKechengleixingNotBetween(String value1, String value2) {
            addCriterion("kechengleixing not between", value1, value2, "kechengleixing");
            return this;
        }

        public Criteria andShoukeshijianIsNull() {
            addCriterion("shoukeshijian is null");
            return this;
        }

        public Criteria andShoukeshijianIsNotNull() {
            addCriterion("shoukeshijian is not null");
            return this;
        }

        public Criteria andShoukeshijianEqualTo(String value) {
            addCriterion("shoukeshijian =", value, "shoukeshijian");
            return this;
        }

        public Criteria andShoukeshijianNotEqualTo(String value) {
            addCriterion("shoukeshijian <>", value, "shoukeshijian");
            return this;
        }

        public Criteria andShoukeshijianGreaterThan(String value) {
            addCriterion("shoukeshijian >", value, "shoukeshijian");
            return this;
        }

        public Criteria andShoukeshijianGreaterThanOrEqualTo(String value) {
            addCriterion("shoukeshijian >=", value, "shoukeshijian");
            return this;
        }

        public Criteria andShoukeshijianLessThan(String value) {
            addCriterion("shoukeshijian <", value, "shoukeshijian");
            return this;
        }

        public Criteria andShoukeshijianLessThanOrEqualTo(String value) {
            addCriterion("shoukeshijian <=", value, "shoukeshijian");
            return this;
        }

        public Criteria andShoukeshijianLike(String value) {
            addCriterion("shoukeshijian like", value, "shoukeshijian");
            return this;
        }

        public Criteria andShoukeshijianNotLike(String value) {
            addCriterion("shoukeshijian not like", value, "shoukeshijian");
            return this;
        }

        public Criteria andShoukeshijianIn(List<String> values) {
            addCriterion("shoukeshijian in", values, "shoukeshijian");
            return this;
        }

        public Criteria andShoukeshijianNotIn(List<String> values) {
            addCriterion("shoukeshijian not in", values, "shoukeshijian");
            return this;
        }

        public Criteria andShoukeshijianBetween(String value1, String value2) {
            addCriterion("shoukeshijian between", value1, value2, "shoukeshijian");
            return this;
        }

        public Criteria andShoukeshijianNotBetween(String value1, String value2) {
            addCriterion("shoukeshijian not between", value1, value2, "shoukeshijian");
            return this;
        }

        public Criteria andKechengmiaoshuIsNull() {
            addCriterion("kechengmiaoshu is null");
            return this;
        }

        public Criteria andKechengmiaoshuIsNotNull() {
            addCriterion("kechengmiaoshu is not null");
            return this;
        }

        public Criteria andKechengmiaoshuEqualTo(String value) {
            addCriterion("kechengmiaoshu =", value, "kechengmiaoshu");
            return this;
        }

        public Criteria andKechengmiaoshuNotEqualTo(String value) {
            addCriterion("kechengmiaoshu <>", value, "kechengmiaoshu");
            return this;
        }

        public Criteria andKechengmiaoshuGreaterThan(String value) {
            addCriterion("kechengmiaoshu >", value, "kechengmiaoshu");
            return this;
        }

        public Criteria andKechengmiaoshuGreaterThanOrEqualTo(String value) {
            addCriterion("kechengmiaoshu >=", value, "kechengmiaoshu");
            return this;
        }

        public Criteria andKechengmiaoshuLessThan(String value) {
            addCriterion("kechengmiaoshu <", value, "kechengmiaoshu");
            return this;
        }

        public Criteria andKechengmiaoshuLessThanOrEqualTo(String value) {
            addCriterion("kechengmiaoshu <=", value, "kechengmiaoshu");
            return this;
        }

        public Criteria andKechengmiaoshuLike(String value) {
            addCriterion("kechengmiaoshu like", value, "kechengmiaoshu");
            return this;
        }

        public Criteria andKechengmiaoshuNotLike(String value) {
            addCriterion("kechengmiaoshu not like", value, "kechengmiaoshu");
            return this;
        }

        public Criteria andKechengmiaoshuIn(List<String> values) {
            addCriterion("kechengmiaoshu in", values, "kechengmiaoshu");
            return this;
        }

        public Criteria andKechengmiaoshuNotIn(List<String> values) {
            addCriterion("kechengmiaoshu not in", values, "kechengmiaoshu");
            return this;
        }

        public Criteria andKechengmiaoshuBetween(String value1, String value2) {
            addCriterion("kechengmiaoshu between", value1, value2, "kechengmiaoshu");
            return this;
        }

        public Criteria andKechengmiaoshuNotBetween(String value1, String value2) {
            addCriterion("kechengmiaoshu not between", value1, value2, "kechengmiaoshu");
            return this;
        }

        public Criteria andOperatoridIsNull() {
            addCriterion("operatorId is null");
            return this;
        }

        public Criteria andOperatoridIsNotNull() {
            addCriterion("operatorId is not null");
            return this;
        }

        public Criteria andOperatoridEqualTo(String value) {
            addCriterion("operatorId =", value, "operatorid");
            return this;
        }

        public Criteria andOperatoridNotEqualTo(String value) {
            addCriterion("operatorId <>", value, "operatorid");
            return this;
        }

        public Criteria andOperatoridGreaterThan(String value) {
            addCriterion("operatorId >", value, "operatorid");
            return this;
        }

        public Criteria andOperatoridGreaterThanOrEqualTo(String value) {
            addCriterion("operatorId >=", value, "operatorid");
            return this;
        }

        public Criteria andOperatoridLessThan(String value) {
            addCriterion("operatorId <", value, "operatorid");
            return this;
        }

        public Criteria andOperatoridLessThanOrEqualTo(String value) {
            addCriterion("operatorId <=", value, "operatorid");
            return this;
        }

        public Criteria andOperatoridLike(String value) {
            addCriterion("operatorId like", value, "operatorid");
            return this;
        }

        public Criteria andOperatoridNotLike(String value) {
            addCriterion("operatorId not like", value, "operatorid");
            return this;
        }

        public Criteria andOperatoridIn(List<String> values) {
            addCriterion("operatorId in", values, "operatorid");
            return this;
        }

        public Criteria andOperatoridNotIn(List<String> values) {
            addCriterion("operatorId not in", values, "operatorid");
            return this;
        }

        public Criteria andOperatoridBetween(String value1, String value2) {
            addCriterion("operatorId between", value1, value2, "operatorid");
            return this;
        }

        public Criteria andOperatoridNotBetween(String value1, String value2) {
            addCriterion("operatorId not between", value1, value2, "operatorid");
            return this;
        }

        public Criteria andItimeIsNull() {
            addCriterion("itime is null");
            return this;
        }

        public Criteria andItimeIsNotNull() {
            addCriterion("itime is not null");
            return this;
        }

        public Criteria andItimeEqualTo(String value) {
            addCriterion("itime =", value, "itime");
            return this;
        }

        public Criteria andItimeNotEqualTo(String value) {
            addCriterion("itime <>", value, "itime");
            return this;
        }

        public Criteria andItimeGreaterThan(String value) {
            addCriterion("itime >", value, "itime");
            return this;
        }

        public Criteria andItimeGreaterThanOrEqualTo(String value) {
            addCriterion("itime >=", value, "itime");
            return this;
        }

        public Criteria andItimeLessThan(String value) {
            addCriterion("itime <", value, "itime");
            return this;
        }

        public Criteria andItimeLessThanOrEqualTo(String value) {
            addCriterion("itime <=", value, "itime");
            return this;
        }

        public Criteria andItimeLike(String value) {
            addCriterion("itime like", value, "itime");
            return this;
        }

        public Criteria andItimeNotLike(String value) {
            addCriterion("itime not like", value, "itime");
            return this;
        }

        public Criteria andItimeIn(List<String> values) {
            addCriterion("itime in", values, "itime");
            return this;
        }

        public Criteria andItimeNotIn(List<String> values) {
            addCriterion("itime not in", values, "itime");
            return this;
        }

        public Criteria andItimeBetween(String value1, String value2) {
            addCriterion("itime between", value1, value2, "itime");
            return this;
        }

        public Criteria andItimeNotBetween(String value1, String value2) {
            addCriterion("itime not between", value1, value2, "itime");
            return this;
        }

        public Criteria andDetailIsNull() {
            addCriterion("detail is null");
            return this;
        }

        public Criteria andDetailIsNotNull() {
            addCriterion("detail is not null");
            return this;
        }

        public Criteria andDetailEqualTo(String value) {
            addCriterion("detail =", value, "detail");
            return this;
        }

        public Criteria andDetailNotEqualTo(String value) {
            addCriterion("detail <>", value, "detail");
            return this;
        }

        public Criteria andDetailGreaterThan(String value) {
            addCriterion("detail >", value, "detail");
            return this;
        }

        public Criteria andDetailGreaterThanOrEqualTo(String value) {
            addCriterion("detail >=", value, "detail");
            return this;
        }

        public Criteria andDetailLessThan(String value) {
            addCriterion("detail <", value, "detail");
            return this;
        }

        public Criteria andDetailLessThanOrEqualTo(String value) {
            addCriterion("detail <=", value, "detail");
            return this;
        }

        public Criteria andDetailLike(String value) {
            addCriterion("detail like", value, "detail");
            return this;
        }

        public Criteria andDetailNotLike(String value) {
            addCriterion("detail not like", value, "detail");
            return this;
        }

        public Criteria andDetailIn(List<String> values) {
            addCriterion("detail in", values, "detail");
            return this;
        }

        public Criteria andDetailNotIn(List<String> values) {
            addCriterion("detail not in", values, "detail");
            return this;
        }

        public Criteria andDetailBetween(String value1, String value2) {
            addCriterion("detail between", value1, value2, "detail");
            return this;
        }

        public Criteria andDetailNotBetween(String value1, String value2) {
            addCriterion("detail not between", value1, value2, "detail");
            return this;
        }

        public Criteria andDeleteflagIsNull() {
            addCriterion("deleteFlag is null");
            return this;
        }

        public Criteria andDeleteflagIsNotNull() {
            addCriterion("deleteFlag is not null");
            return this;
        }

        public Criteria andDeleteflagEqualTo(Integer value) {
            addCriterion("deleteFlag =", value, "deleteflag");
            return this;
        }

        public Criteria andDeleteflagNotEqualTo(Integer value) {
            addCriterion("deleteFlag <>", value, "deleteflag");
            return this;
        }

        public Criteria andDeleteflagGreaterThan(Integer value) {
            addCriterion("deleteFlag >", value, "deleteflag");
            return this;
        }

        public Criteria andDeleteflagGreaterThanOrEqualTo(Integer value) {
            addCriterion("deleteFlag >=", value, "deleteflag");
            return this;
        }

        public Criteria andDeleteflagLessThan(Integer value) {
            addCriterion("deleteFlag <", value, "deleteflag");
            return this;
        }

        public Criteria andDeleteflagLessThanOrEqualTo(Integer value) {
            addCriterion("deleteFlag <=", value, "deleteflag");
            return this;
        }

        public Criteria andDeleteflagIn(List<Integer> values) {
            addCriterion("deleteFlag in", values, "deleteflag");
            return this;
        }

        public Criteria andDeleteflagNotIn(List<Integer> values) {
            addCriterion("deleteFlag not in", values, "deleteflag");
            return this;
        }

        public Criteria andDeleteflagBetween(Integer value1, Integer value2) {
            addCriterion("deleteFlag between", value1, value2, "deleteflag");
            return this;
        }

        public Criteria andDeleteflagNotBetween(Integer value1, Integer value2) {
            addCriterion("deleteFlag not between", value1, value2, "deleteflag");
            return this;
        }

        public Criteria andErjiguanlianzdIsNull() {
            addCriterion("erjiguanlianzd is null");
            return this;
        }

        public Criteria andErjiguanlianzdIsNotNull() {
            addCriterion("erjiguanlianzd is not null");
            return this;
        }

        public Criteria andErjiguanlianzdEqualTo(String value) {
            addCriterion("erjiguanlianzd =", value, "erjiguanlianzd");
            return this;
        }

        public Criteria andErjiguanlianzdNotEqualTo(String value) {
            addCriterion("erjiguanlianzd <>", value, "erjiguanlianzd");
            return this;
        }

        public Criteria andErjiguanlianzdGreaterThan(String value) {
            addCriterion("erjiguanlianzd >", value, "erjiguanlianzd");
            return this;
        }

        public Criteria andErjiguanlianzdGreaterThanOrEqualTo(String value) {
            addCriterion("erjiguanlianzd >=", value, "erjiguanlianzd");
            return this;
        }

        public Criteria andErjiguanlianzdLessThan(String value) {
            addCriterion("erjiguanlianzd <", value, "erjiguanlianzd");
            return this;
        }

        public Criteria andErjiguanlianzdLessThanOrEqualTo(String value) {
            addCriterion("erjiguanlianzd <=", value, "erjiguanlianzd");
            return this;
        }

        public Criteria andErjiguanlianzdLike(String value) {
            addCriterion("erjiguanlianzd like", value, "erjiguanlianzd");
            return this;
        }

        public Criteria andErjiguanlianzdNotLike(String value) {
            addCriterion("erjiguanlianzd not like", value, "erjiguanlianzd");
            return this;
        }

        public Criteria andErjiguanlianzdIn(List<String> values) {
            addCriterion("erjiguanlianzd in", values, "erjiguanlianzd");
            return this;
        }

        public Criteria andErjiguanlianzdNotIn(List<String> values) {
            addCriterion("erjiguanlianzd not in", values, "erjiguanlianzd");
            return this;
        }

        public Criteria andErjiguanlianzdBetween(String value1, String value2) {
            addCriterion("erjiguanlianzd between", value1, value2, "erjiguanlianzd");
            return this;
        }

        public Criteria andErjiguanlianzdNotBetween(String value1, String value2) {
            addCriterion("erjiguanlianzd not between", value1, value2, "erjiguanlianzd");
            return this;
        }
    }
}