package bean;

public class paikexinxiBean {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column paikexinxi.id
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column paikexinxi.jiaolianmingchen
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String jiaolianmingchen;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column paikexinxi.jiaoliandengji
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String jiaoliandengji;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column paikexinxi.shoukemingchen
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String shoukemingchen;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column paikexinxi.kechengleixing
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String kechengleixing;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column paikexinxi.shoukeshijian
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String shoukeshijian;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column paikexinxi.kechengmiaoshu
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String kechengmiaoshu;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column paikexinxi.operatorId
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String operatorid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column paikexinxi.itime
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String itime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column paikexinxi.detail
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String detail;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column paikexinxi.deleteFlag
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private Integer deleteflag;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column paikexinxi.erjiguanlianzd
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String erjiguanlianzd;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column paikexinxi.id
     *
     * @return the value of paikexinxi.id
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column paikexinxi.id
     *
     * @param id the value for paikexinxi.id
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column paikexinxi.jiaolianmingchen
     *
     * @return the value of paikexinxi.jiaolianmingchen
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getJiaolianmingchen() {
        return jiaolianmingchen;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column paikexinxi.jiaolianmingchen
     *
     * @param jiaolianmingchen the value for paikexinxi.jiaolianmingchen
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setJiaolianmingchen(String jiaolianmingchen) {
        this.jiaolianmingchen = jiaolianmingchen;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column paikexinxi.jiaoliandengji
     *
     * @return the value of paikexinxi.jiaoliandengji
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getJiaoliandengji() {
        return jiaoliandengji;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column paikexinxi.jiaoliandengji
     *
     * @param jiaoliandengji the value for paikexinxi.jiaoliandengji
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setJiaoliandengji(String jiaoliandengji) {
        this.jiaoliandengji = jiaoliandengji;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column paikexinxi.shoukemingchen
     *
     * @return the value of paikexinxi.shoukemingchen
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getShoukemingchen() {
        return shoukemingchen;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column paikexinxi.shoukemingchen
     *
     * @param shoukemingchen the value for paikexinxi.shoukemingchen
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setShoukemingchen(String shoukemingchen) {
        this.shoukemingchen = shoukemingchen;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column paikexinxi.kechengleixing
     *
     * @return the value of paikexinxi.kechengleixing
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getKechengleixing() {
        return kechengleixing;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column paikexinxi.kechengleixing
     *
     * @param kechengleixing the value for paikexinxi.kechengleixing
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setKechengleixing(String kechengleixing) {
        this.kechengleixing = kechengleixing;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column paikexinxi.shoukeshijian
     *
     * @return the value of paikexinxi.shoukeshijian
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getShoukeshijian() {
        return shoukeshijian;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column paikexinxi.shoukeshijian
     *
     * @param shoukeshijian the value for paikexinxi.shoukeshijian
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setShoukeshijian(String shoukeshijian) {
        this.shoukeshijian = shoukeshijian;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column paikexinxi.kechengmiaoshu
     *
     * @return the value of paikexinxi.kechengmiaoshu
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getKechengmiaoshu() {
        return kechengmiaoshu;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column paikexinxi.kechengmiaoshu
     *
     * @param kechengmiaoshu the value for paikexinxi.kechengmiaoshu
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setKechengmiaoshu(String kechengmiaoshu) {
        this.kechengmiaoshu = kechengmiaoshu;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column paikexinxi.operatorId
     *
     * @return the value of paikexinxi.operatorId
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getOperatorid() {
        return operatorid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column paikexinxi.operatorId
     *
     * @param operatorid the value for paikexinxi.operatorId
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setOperatorid(String operatorid) {
        this.operatorid = operatorid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column paikexinxi.itime
     *
     * @return the value of paikexinxi.itime
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getItime() {
        return itime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column paikexinxi.itime
     *
     * @param itime the value for paikexinxi.itime
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setItime(String itime) {
        this.itime = itime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column paikexinxi.detail
     *
     * @return the value of paikexinxi.detail
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column paikexinxi.detail
     *
     * @param detail the value for paikexinxi.detail
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setDetail(String detail) {
        this.detail = detail;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column paikexinxi.deleteFlag
     *
     * @return the value of paikexinxi.deleteFlag
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public Integer getDeleteflag() {
        return deleteflag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column paikexinxi.deleteFlag
     *
     * @param deleteflag the value for paikexinxi.deleteFlag
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setDeleteflag(Integer deleteflag) {
        this.deleteflag = deleteflag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column paikexinxi.erjiguanlianzd
     *
     * @return the value of paikexinxi.erjiguanlianzd
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getErjiguanlianzd() {
        return erjiguanlianzd;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column paikexinxi.erjiguanlianzd
     *
     * @param erjiguanlianzd the value for paikexinxi.erjiguanlianzd
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setErjiguanlianzd(String erjiguanlianzd) {
        this.erjiguanlianzd = erjiguanlianzd;
    }
}