package bean;

public class role_menuBean {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column role_menu.id
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column role_menu.role_id
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private Integer roleId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column role_menu.menu_id
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private Integer menuId;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column role_menu.id
     *
     * @return the value of role_menu.id
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column role_menu.id
     *
     * @param id the value for role_menu.id
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column role_menu.role_id
     *
     * @return the value of role_menu.role_id
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column role_menu.role_id
     *
     * @param roleId the value for role_menu.role_id
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column role_menu.menu_id
     *
     * @return the value of role_menu.menu_id
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column role_menu.menu_id
     *
     * @param menuId the value for role_menu.menu_id
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }
}