package bean;

public class shouyehuandengpianBean {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column shouyehuandengpian.id
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column shouyehuandengpian.tupianmingcheng
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String tupianmingcheng;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column shouyehuandengpian.tupianbianhao
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String tupianbianhao;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column shouyehuandengpian.changd
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String changd;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column shouyehuandengpian.kuandu
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String kuandu;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column shouyehuandengpian.fuJian
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String fujian;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column shouyehuandengpian.operatorId
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String operatorid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column shouyehuandengpian.itime
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String itime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column shouyehuandengpian.detail
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String detail;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column shouyehuandengpian.deleteFlag
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private Integer deleteflag;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column shouyehuandengpian.id
     *
     * @return the value of shouyehuandengpian.id
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column shouyehuandengpian.id
     *
     * @param id the value for shouyehuandengpian.id
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column shouyehuandengpian.tupianmingcheng
     *
     * @return the value of shouyehuandengpian.tupianmingcheng
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getTupianmingcheng() {
        return tupianmingcheng;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column shouyehuandengpian.tupianmingcheng
     *
     * @param tupianmingcheng the value for shouyehuandengpian.tupianmingcheng
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setTupianmingcheng(String tupianmingcheng) {
        this.tupianmingcheng = tupianmingcheng;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column shouyehuandengpian.tupianbianhao
     *
     * @return the value of shouyehuandengpian.tupianbianhao
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getTupianbianhao() {
        return tupianbianhao;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column shouyehuandengpian.tupianbianhao
     *
     * @param tupianbianhao the value for shouyehuandengpian.tupianbianhao
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setTupianbianhao(String tupianbianhao) {
        this.tupianbianhao = tupianbianhao;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column shouyehuandengpian.changd
     *
     * @return the value of shouyehuandengpian.changd
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getChangd() {
        return changd;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column shouyehuandengpian.changd
     *
     * @param changd the value for shouyehuandengpian.changd
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setChangd(String changd) {
        this.changd = changd;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column shouyehuandengpian.kuandu
     *
     * @return the value of shouyehuandengpian.kuandu
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getKuandu() {
        return kuandu;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column shouyehuandengpian.kuandu
     *
     * @param kuandu the value for shouyehuandengpian.kuandu
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setKuandu(String kuandu) {
        this.kuandu = kuandu;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column shouyehuandengpian.fuJian
     *
     * @return the value of shouyehuandengpian.fuJian
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getFujian() {
        return fujian;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column shouyehuandengpian.fuJian
     *
     * @param fujian the value for shouyehuandengpian.fuJian
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setFujian(String fujian) {
        this.fujian = fujian;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column shouyehuandengpian.operatorId
     *
     * @return the value of shouyehuandengpian.operatorId
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getOperatorid() {
        return operatorid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column shouyehuandengpian.operatorId
     *
     * @param operatorid the value for shouyehuandengpian.operatorId
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setOperatorid(String operatorid) {
        this.operatorid = operatorid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column shouyehuandengpian.itime
     *
     * @return the value of shouyehuandengpian.itime
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getItime() {
        return itime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column shouyehuandengpian.itime
     *
     * @param itime the value for shouyehuandengpian.itime
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setItime(String itime) {
        this.itime = itime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column shouyehuandengpian.detail
     *
     * @return the value of shouyehuandengpian.detail
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column shouyehuandengpian.detail
     *
     * @param detail the value for shouyehuandengpian.detail
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setDetail(String detail) {
        this.detail = detail;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column shouyehuandengpian.deleteFlag
     *
     * @return the value of shouyehuandengpian.deleteFlag
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public Integer getDeleteflag() {
        return deleteflag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column shouyehuandengpian.deleteFlag
     *
     * @param deleteflag the value for shouyehuandengpian.deleteFlag
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setDeleteflag(Integer deleteflag) {
        this.deleteflag = deleteflag;
    }
}