package bean;

public class shoukeshijianduanBean {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column shoukeshijianduan.id
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column shoukeshijianduan.shijianduan
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String shijianduan;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column shoukeshijianduan.operatorId
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String operatorid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column shoukeshijianduan.itime
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String itime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column shoukeshijianduan.detail
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String detail;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column shoukeshijianduan.deleteFlag
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private Integer deleteflag;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column shoukeshijianduan.erjiguanlianzd
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String erjiguanlianzd;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column shoukeshijianduan.id
     *
     * @return the value of shoukeshijianduan.id
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column shoukeshijianduan.id
     *
     * @param id the value for shoukeshijianduan.id
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column shoukeshijianduan.shijianduan
     *
     * @return the value of shoukeshijianduan.shijianduan
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getShijianduan() {
        return shijianduan;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column shoukeshijianduan.shijianduan
     *
     * @param shijianduan the value for shoukeshijianduan.shijianduan
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setShijianduan(String shijianduan) {
        this.shijianduan = shijianduan;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column shoukeshijianduan.operatorId
     *
     * @return the value of shoukeshijianduan.operatorId
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getOperatorid() {
        return operatorid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column shoukeshijianduan.operatorId
     *
     * @param operatorid the value for shoukeshijianduan.operatorId
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setOperatorid(String operatorid) {
        this.operatorid = operatorid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column shoukeshijianduan.itime
     *
     * @return the value of shoukeshijianduan.itime
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getItime() {
        return itime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column shoukeshijianduan.itime
     *
     * @param itime the value for shoukeshijianduan.itime
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setItime(String itime) {
        this.itime = itime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column shoukeshijianduan.detail
     *
     * @return the value of shoukeshijianduan.detail
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column shoukeshijianduan.detail
     *
     * @param detail the value for shoukeshijianduan.detail
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setDetail(String detail) {
        this.detail = detail;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column shoukeshijianduan.deleteFlag
     *
     * @return the value of shoukeshijianduan.deleteFlag
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public Integer getDeleteflag() {
        return deleteflag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column shoukeshijianduan.deleteFlag
     *
     * @param deleteflag the value for shoukeshijianduan.deleteFlag
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setDeleteflag(Integer deleteflag) {
        this.deleteflag = deleteflag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column shoukeshijianduan.erjiguanlianzd
     *
     * @return the value of shoukeshijianduan.erjiguanlianzd
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getErjiguanlianzd() {
        return erjiguanlianzd;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column shoukeshijianduan.erjiguanlianzd
     *
     * @param erjiguanlianzd the value for shoukeshijianduan.erjiguanlianzd
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setErjiguanlianzd(String erjiguanlianzd) {
        this.erjiguanlianzd = erjiguanlianzd;
    }
}