package bean;

public class system_infoBean {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column system_info.id
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column system_info.systemName
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String systemname;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column system_info.systemDesigner
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String systemdesigner;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column system_info.loginPageStyle
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String loginpagestyle;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column system_info.systemSkin
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String systemskin;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column system_info.systemSkinName
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String systemskinname;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column system_info.topPanDisplay
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String toppandisplay;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column system_info.southPanDisplay
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String southpandisplay;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column system_info.menuRegion
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String menuregion;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column system_info.menuCollapse
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String menucollapse;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column system_info.menuAnimate
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String menuanimate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column system_info.menuBackground
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String menubackground;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column system_info.isApprove
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String isapprove;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column system_info.houTaiZhuTi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String houtaizhuti;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column system_info.qianTaiZhuTi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String qiantaizhuti;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column system_info.buttonPlace
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String buttonplace;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column system_info.searchPlace
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String searchplace;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column system_info.id
     *
     * @return the value of system_info.id
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column system_info.id
     *
     * @param id the value for system_info.id
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column system_info.systemName
     *
     * @return the value of system_info.systemName
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getSystemname() {
        return systemname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column system_info.systemName
     *
     * @param systemname the value for system_info.systemName
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setSystemname(String systemname) {
        this.systemname = systemname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column system_info.systemDesigner
     *
     * @return the value of system_info.systemDesigner
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getSystemdesigner() {
        return systemdesigner;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column system_info.systemDesigner
     *
     * @param systemdesigner the value for system_info.systemDesigner
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setSystemdesigner(String systemdesigner) {
        this.systemdesigner = systemdesigner;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column system_info.loginPageStyle
     *
     * @return the value of system_info.loginPageStyle
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getLoginpagestyle() {
        return loginpagestyle;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column system_info.loginPageStyle
     *
     * @param loginpagestyle the value for system_info.loginPageStyle
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setLoginpagestyle(String loginpagestyle) {
        this.loginpagestyle = loginpagestyle;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column system_info.systemSkin
     *
     * @return the value of system_info.systemSkin
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getSystemskin() {
        return systemskin;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column system_info.systemSkin
     *
     * @param systemskin the value for system_info.systemSkin
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setSystemskin(String systemskin) {
        this.systemskin = systemskin;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column system_info.systemSkinName
     *
     * @return the value of system_info.systemSkinName
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getSystemskinname() {
        return systemskinname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column system_info.systemSkinName
     *
     * @param systemskinname the value for system_info.systemSkinName
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setSystemskinname(String systemskinname) {
        this.systemskinname = systemskinname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column system_info.topPanDisplay
     *
     * @return the value of system_info.topPanDisplay
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getToppandisplay() {
        return toppandisplay;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column system_info.topPanDisplay
     *
     * @param toppandisplay the value for system_info.topPanDisplay
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setToppandisplay(String toppandisplay) {
        this.toppandisplay = toppandisplay;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column system_info.southPanDisplay
     *
     * @return the value of system_info.southPanDisplay
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getSouthpandisplay() {
        return southpandisplay;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column system_info.southPanDisplay
     *
     * @param southpandisplay the value for system_info.southPanDisplay
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setSouthpandisplay(String southpandisplay) {
        this.southpandisplay = southpandisplay;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column system_info.menuRegion
     *
     * @return the value of system_info.menuRegion
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getMenuregion() {
        return menuregion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column system_info.menuRegion
     *
     * @param menuregion the value for system_info.menuRegion
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setMenuregion(String menuregion) {
        this.menuregion = menuregion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column system_info.menuCollapse
     *
     * @return the value of system_info.menuCollapse
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getMenucollapse() {
        return menucollapse;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column system_info.menuCollapse
     *
     * @param menucollapse the value for system_info.menuCollapse
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setMenucollapse(String menucollapse) {
        this.menucollapse = menucollapse;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column system_info.menuAnimate
     *
     * @return the value of system_info.menuAnimate
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getMenuanimate() {
        return menuanimate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column system_info.menuAnimate
     *
     * @param menuanimate the value for system_info.menuAnimate
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setMenuanimate(String menuanimate) {
        this.menuanimate = menuanimate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column system_info.menuBackground
     *
     * @return the value of system_info.menuBackground
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getMenubackground() {
        return menubackground;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column system_info.menuBackground
     *
     * @param menubackground the value for system_info.menuBackground
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setMenubackground(String menubackground) {
        this.menubackground = menubackground;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column system_info.isApprove
     *
     * @return the value of system_info.isApprove
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getIsapprove() {
        return isapprove;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column system_info.isApprove
     *
     * @param isapprove the value for system_info.isApprove
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setIsapprove(String isapprove) {
        this.isapprove = isapprove;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column system_info.houTaiZhuTi
     *
     * @return the value of system_info.houTaiZhuTi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getHoutaizhuti() {
        return houtaizhuti;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column system_info.houTaiZhuTi
     *
     * @param houtaizhuti the value for system_info.houTaiZhuTi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setHoutaizhuti(String houtaizhuti) {
        this.houtaizhuti = houtaizhuti;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column system_info.qianTaiZhuTi
     *
     * @return the value of system_info.qianTaiZhuTi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getQiantaizhuti() {
        return qiantaizhuti;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column system_info.qianTaiZhuTi
     *
     * @param qiantaizhuti the value for system_info.qianTaiZhuTi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setQiantaizhuti(String qiantaizhuti) {
        this.qiantaizhuti = qiantaizhuti;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column system_info.buttonPlace
     *
     * @return the value of system_info.buttonPlace
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getButtonplace() {
        return buttonplace;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column system_info.buttonPlace
     *
     * @param buttonplace the value for system_info.buttonPlace
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setButtonplace(String buttonplace) {
        this.buttonplace = buttonplace;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column system_info.searchPlace
     *
     * @return the value of system_info.searchPlace
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getSearchplace() {
        return searchplace;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column system_info.searchPlace
     *
     * @param searchplace the value for system_info.searchPlace
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setSearchplace(String searchplace) {
        this.searchplace = searchplace;
    }
}