package bean;

public class systemrolemanageBean {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column systemrolemanage.id
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column systemrolemanage.jiaosemingchen
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String jiaosemingchen;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column systemrolemanage.operatorId
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String operatorid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column systemrolemanage.itime
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String itime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column systemrolemanage.detail
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String detail;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column systemrolemanage.deleteFlag
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private Integer deleteflag;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column systemrolemanage.erjiguanlianzd
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String erjiguanlianzd;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column systemrolemanage.id
     *
     * @return the value of systemrolemanage.id
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column systemrolemanage.id
     *
     * @param id the value for systemrolemanage.id
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column systemrolemanage.jiaosemingchen
     *
     * @return the value of systemrolemanage.jiaosemingchen
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getJiaosemingchen() {
        return jiaosemingchen;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column systemrolemanage.jiaosemingchen
     *
     * @param jiaosemingchen the value for systemrolemanage.jiaosemingchen
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setJiaosemingchen(String jiaosemingchen) {
        this.jiaosemingchen = jiaosemingchen;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column systemrolemanage.operatorId
     *
     * @return the value of systemrolemanage.operatorId
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getOperatorid() {
        return operatorid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column systemrolemanage.operatorId
     *
     * @param operatorid the value for systemrolemanage.operatorId
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setOperatorid(String operatorid) {
        this.operatorid = operatorid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column systemrolemanage.itime
     *
     * @return the value of systemrolemanage.itime
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getItime() {
        return itime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column systemrolemanage.itime
     *
     * @param itime the value for systemrolemanage.itime
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setItime(String itime) {
        this.itime = itime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column systemrolemanage.detail
     *
     * @return the value of systemrolemanage.detail
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column systemrolemanage.detail
     *
     * @param detail the value for systemrolemanage.detail
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setDetail(String detail) {
        this.detail = detail;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column systemrolemanage.deleteFlag
     *
     * @return the value of systemrolemanage.deleteFlag
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public Integer getDeleteflag() {
        return deleteflag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column systemrolemanage.deleteFlag
     *
     * @param deleteflag the value for systemrolemanage.deleteFlag
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setDeleteflag(Integer deleteflag) {
        this.deleteflag = deleteflag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column systemrolemanage.erjiguanlianzd
     *
     * @return the value of systemrolemanage.erjiguanlianzd
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getErjiguanlianzd() {
        return erjiguanlianzd;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column systemrolemanage.erjiguanlianzd
     *
     * @param erjiguanlianzd the value for systemrolemanage.erjiguanlianzd
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setErjiguanlianzd(String erjiguanlianzd) {
        this.erjiguanlianzd = erjiguanlianzd;
    }
}