package bean;

public class table_tongjiBean {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column table_tongji.id
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column table_tongji.table_name
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String tableName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column table_tongji.field_name
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String fieldName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column table_tongji.tongji
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String tongji;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column table_tongji.id
     *
     * @return the value of table_tongji.id
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column table_tongji.id
     *
     * @param id the value for table_tongji.id
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column table_tongji.table_name
     *
     * @return the value of table_tongji.table_name
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column table_tongji.table_name
     *
     * @param tableName the value for table_tongji.table_name
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column table_tongji.field_name
     *
     * @return the value of table_tongji.field_name
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getFieldName() {
        return fieldName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column table_tongji.field_name
     *
     * @param fieldName the value for table_tongji.field_name
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setFieldName(String fieldName) {
        this.fieldName = fieldName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column table_tongji.tongji
     *
     * @return the value of table_tongji.tongji
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getTongji() {
        return tongji;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column table_tongji.tongji
     *
     * @param tongji the value for table_tongji.tongji
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setTongji(String tongji) {
        this.tongji = tongji;
    }
}