package bean;

public class table_guanlianBean {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column table_guanlian.id
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column table_guanlian.table_name
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String tableName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column table_guanlian.field_name
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String fieldName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column table_guanlian.guanlianbiao
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String guanlianbiao;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column table_guanlian.guanlianziduan
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String guanlianziduan;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column table_guanlian.guanlian
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private Integer guanlian;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column table_guanlian.bitian
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private Integer bitian;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column table_guanlian.zhidu
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private Integer zhidu;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column table_guanlian.morenzhi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String morenzhi;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column table_guanlian.ziduanleixing
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String ziduanleixing;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column table_guanlian.id
     *
     * @return the value of table_guanlian.id
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column table_guanlian.id
     *
     * @param id the value for table_guanlian.id
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column table_guanlian.table_name
     *
     * @return the value of table_guanlian.table_name
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column table_guanlian.table_name
     *
     * @param tableName the value for table_guanlian.table_name
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column table_guanlian.field_name
     *
     * @return the value of table_guanlian.field_name
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getFieldName() {
        return fieldName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column table_guanlian.field_name
     *
     * @param fieldName the value for table_guanlian.field_name
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setFieldName(String fieldName) {
        this.fieldName = fieldName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column table_guanlian.guanlianbiao
     *
     * @return the value of table_guanlian.guanlianbiao
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getGuanlianbiao() {
        return guanlianbiao;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column table_guanlian.guanlianbiao
     *
     * @param guanlianbiao the value for table_guanlian.guanlianbiao
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setGuanlianbiao(String guanlianbiao) {
        this.guanlianbiao = guanlianbiao;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column table_guanlian.guanlianziduan
     *
     * @return the value of table_guanlian.guanlianziduan
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getGuanlianziduan() {
        return guanlianziduan;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column table_guanlian.guanlianziduan
     *
     * @param guanlianziduan the value for table_guanlian.guanlianziduan
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setGuanlianziduan(String guanlianziduan) {
        this.guanlianziduan = guanlianziduan;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column table_guanlian.guanlian
     *
     * @return the value of table_guanlian.guanlian
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public Integer getGuanlian() {
        return guanlian;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column table_guanlian.guanlian
     *
     * @param guanlian the value for table_guanlian.guanlian
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setGuanlian(Integer guanlian) {
        this.guanlian = guanlian;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column table_guanlian.bitian
     *
     * @return the value of table_guanlian.bitian
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public Integer getBitian() {
        return bitian;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column table_guanlian.bitian
     *
     * @param bitian the value for table_guanlian.bitian
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setBitian(Integer bitian) {
        this.bitian = bitian;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column table_guanlian.zhidu
     *
     * @return the value of table_guanlian.zhidu
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public Integer getZhidu() {
        return zhidu;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column table_guanlian.zhidu
     *
     * @param zhidu the value for table_guanlian.zhidu
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setZhidu(Integer zhidu) {
        this.zhidu = zhidu;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column table_guanlian.morenzhi
     *
     * @return the value of table_guanlian.morenzhi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getMorenzhi() {
        return morenzhi;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column table_guanlian.morenzhi
     *
     * @param morenzhi the value for table_guanlian.morenzhi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setMorenzhi(String morenzhi) {
        this.morenzhi = morenzhi;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column table_guanlian.ziduanleixing
     *
     * @return the value of table_guanlian.ziduanleixing
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getZiduanleixing() {
        return ziduanleixing;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column table_guanlian.ziduanleixing
     *
     * @param ziduanleixing the value for table_guanlian.ziduanleixing
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setZiduanleixing(String ziduanleixing) {
        this.ziduanleixing = ziduanleixing;
    }
}