package bean;

public class user_infoBean {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user_info.Id
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user_info.userAcct
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String useracct;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user_info.userPass
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String userpass;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user_info.deleteFlag
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private Integer deleteflag;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user_info.userName
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String username;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user_info.userType
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private Integer usertype;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user_info.status
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private Integer status;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user_info.Id
     *
     * @return the value of user_info.Id
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user_info.Id
     *
     * @param id the value for user_info.Id
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user_info.userAcct
     *
     * @return the value of user_info.userAcct
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getUseracct() {
        return useracct;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user_info.userAcct
     *
     * @param useracct the value for user_info.userAcct
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setUseracct(String useracct) {
        this.useracct = useracct;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user_info.userPass
     *
     * @return the value of user_info.userPass
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getUserpass() {
        return userpass;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user_info.userPass
     *
     * @param userpass the value for user_info.userPass
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setUserpass(String userpass) {
        this.userpass = userpass;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user_info.deleteFlag
     *
     * @return the value of user_info.deleteFlag
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public Integer getDeleteflag() {
        return deleteflag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user_info.deleteFlag
     *
     * @param deleteflag the value for user_info.deleteFlag
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setDeleteflag(Integer deleteflag) {
        this.deleteflag = deleteflag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user_info.userName
     *
     * @return the value of user_info.userName
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user_info.userName
     *
     * @param username the value for user_info.userName
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user_info.userType
     *
     * @return the value of user_info.userType
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public Integer getUsertype() {
        return usertype;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user_info.userType
     *
     * @param usertype the value for user_info.userType
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setUsertype(Integer usertype) {
        this.usertype = usertype;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user_info.status
     *
     * @return the value of user_info.status
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user_info.status
     *
     * @param status the value for user_info.status
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}