package bean;

public class user_info_detailBean {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user_info_detail.Id
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user_info_detail.userSex
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String usersex;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user_info_detail.userAge
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private Integer userage;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user_info_detail.registerTime
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String registertime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user_info_detail.userId
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private Integer userid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user_info_detail.userPhone
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String userphone;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user_info_detail.userName
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String username;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user_info_detail.userDetail
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String userdetail;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user_info_detail.userDoc
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String userdoc;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user_info_detail.danwei
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String danwei;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user_info_detail.bumen
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String bumen;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user_info_detail.zhiwei
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String zhiwei;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user_info_detail.idcard
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String idcard;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user_info_detail.Id
     *
     * @return the value of user_info_detail.Id
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user_info_detail.Id
     *
     * @param id the value for user_info_detail.Id
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user_info_detail.userSex
     *
     * @return the value of user_info_detail.userSex
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getUsersex() {
        return usersex;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user_info_detail.userSex
     *
     * @param usersex the value for user_info_detail.userSex
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setUsersex(String usersex) {
        this.usersex = usersex;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user_info_detail.userAge
     *
     * @return the value of user_info_detail.userAge
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public Integer getUserage() {
        return userage;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user_info_detail.userAge
     *
     * @param userage the value for user_info_detail.userAge
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setUserage(Integer userage) {
        this.userage = userage;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user_info_detail.registerTime
     *
     * @return the value of user_info_detail.registerTime
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getRegistertime() {
        return registertime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user_info_detail.registerTime
     *
     * @param registertime the value for user_info_detail.registerTime
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setRegistertime(String registertime) {
        this.registertime = registertime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user_info_detail.userId
     *
     * @return the value of user_info_detail.userId
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user_info_detail.userId
     *
     * @param userid the value for user_info_detail.userId
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user_info_detail.userPhone
     *
     * @return the value of user_info_detail.userPhone
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getUserphone() {
        return userphone;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user_info_detail.userPhone
     *
     * @param userphone the value for user_info_detail.userPhone
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setUserphone(String userphone) {
        this.userphone = userphone;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user_info_detail.userName
     *
     * @return the value of user_info_detail.userName
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user_info_detail.userName
     *
     * @param username the value for user_info_detail.userName
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user_info_detail.userDetail
     *
     * @return the value of user_info_detail.userDetail
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getUserdetail() {
        return userdetail;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user_info_detail.userDetail
     *
     * @param userdetail the value for user_info_detail.userDetail
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setUserdetail(String userdetail) {
        this.userdetail = userdetail;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user_info_detail.userDoc
     *
     * @return the value of user_info_detail.userDoc
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getUserdoc() {
        return userdoc;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user_info_detail.userDoc
     *
     * @param userdoc the value for user_info_detail.userDoc
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setUserdoc(String userdoc) {
        this.userdoc = userdoc;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user_info_detail.danwei
     *
     * @return the value of user_info_detail.danwei
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getDanwei() {
        return danwei;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user_info_detail.danwei
     *
     * @param danwei the value for user_info_detail.danwei
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setDanwei(String danwei) {
        this.danwei = danwei;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user_info_detail.bumen
     *
     * @return the value of user_info_detail.bumen
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getBumen() {
        return bumen;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user_info_detail.bumen
     *
     * @param bumen the value for user_info_detail.bumen
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setBumen(String bumen) {
        this.bumen = bumen;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user_info_detail.zhiwei
     *
     * @return the value of user_info_detail.zhiwei
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getZhiwei() {
        return zhiwei;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user_info_detail.zhiwei
     *
     * @param zhiwei the value for user_info_detail.zhiwei
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setZhiwei(String zhiwei) {
        this.zhiwei = zhiwei;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user_info_detail.idcard
     *
     * @return the value of user_info_detail.idcard
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user_info_detail.idcard
     *
     * @param idcard the value for user_info_detail.idcard
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard;
    }
}