package bean;

public class user_menuBean {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user_menu.Id
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user_menu.user_id
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user_menu.menu_id
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private Integer menuId;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user_menu.Id
     *
     * @return the value of user_menu.Id
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user_menu.Id
     *
     * @param id the value for user_menu.Id
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user_menu.user_id
     *
     * @return the value of user_menu.user_id
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user_menu.user_id
     *
     * @param userId the value for user_menu.user_id
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user_menu.menu_id
     *
     * @return the value of user_menu.menu_id
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user_menu.menu_id
     *
     * @param menuId the value for user_menu.menu_id
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }
}