package bean;

public class xiaofeiqiandaoBean {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column xiaofeiqiandao.id
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column xiaofeiqiandao.huiyuanzhanghao
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String huiyuanzhanghao;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column xiaofeiqiandao.xiaofeiriqi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String xiaofeiriqi;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column xiaofeiqiandao.shouliren
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String shouliren;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column xiaofeiqiandao.shoulishijian
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String shoulishijian;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column xiaofeiqiandao.operatorId
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String operatorid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column xiaofeiqiandao.itime
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String itime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column xiaofeiqiandao.detail
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String detail;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column xiaofeiqiandao.deleteFlag
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private Integer deleteflag;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column xiaofeiqiandao.erjiguanlianzd
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String erjiguanlianzd;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column xiaofeiqiandao.id
     *
     * @return the value of xiaofeiqiandao.id
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column xiaofeiqiandao.id
     *
     * @param id the value for xiaofeiqiandao.id
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column xiaofeiqiandao.huiyuanzhanghao
     *
     * @return the value of xiaofeiqiandao.huiyuanzhanghao
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getHuiyuanzhanghao() {
        return huiyuanzhanghao;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column xiaofeiqiandao.huiyuanzhanghao
     *
     * @param huiyuanzhanghao the value for xiaofeiqiandao.huiyuanzhanghao
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setHuiyuanzhanghao(String huiyuanzhanghao) {
        this.huiyuanzhanghao = huiyuanzhanghao;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column xiaofeiqiandao.xiaofeiriqi
     *
     * @return the value of xiaofeiqiandao.xiaofeiriqi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getXiaofeiriqi() {
        return xiaofeiriqi;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column xiaofeiqiandao.xiaofeiriqi
     *
     * @param xiaofeiriqi the value for xiaofeiqiandao.xiaofeiriqi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setXiaofeiriqi(String xiaofeiriqi) {
        this.xiaofeiriqi = xiaofeiriqi;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column xiaofeiqiandao.shouliren
     *
     * @return the value of xiaofeiqiandao.shouliren
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getShouliren() {
        return shouliren;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column xiaofeiqiandao.shouliren
     *
     * @param shouliren the value for xiaofeiqiandao.shouliren
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setShouliren(String shouliren) {
        this.shouliren = shouliren;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column xiaofeiqiandao.shoulishijian
     *
     * @return the value of xiaofeiqiandao.shoulishijian
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getShoulishijian() {
        return shoulishijian;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column xiaofeiqiandao.shoulishijian
     *
     * @param shoulishijian the value for xiaofeiqiandao.shoulishijian
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setShoulishijian(String shoulishijian) {
        this.shoulishijian = shoulishijian;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column xiaofeiqiandao.operatorId
     *
     * @return the value of xiaofeiqiandao.operatorId
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getOperatorid() {
        return operatorid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column xiaofeiqiandao.operatorId
     *
     * @param operatorid the value for xiaofeiqiandao.operatorId
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setOperatorid(String operatorid) {
        this.operatorid = operatorid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column xiaofeiqiandao.itime
     *
     * @return the value of xiaofeiqiandao.itime
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getItime() {
        return itime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column xiaofeiqiandao.itime
     *
     * @param itime the value for xiaofeiqiandao.itime
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setItime(String itime) {
        this.itime = itime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column xiaofeiqiandao.detail
     *
     * @return the value of xiaofeiqiandao.detail
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column xiaofeiqiandao.detail
     *
     * @param detail the value for xiaofeiqiandao.detail
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setDetail(String detail) {
        this.detail = detail;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column xiaofeiqiandao.deleteFlag
     *
     * @return the value of xiaofeiqiandao.deleteFlag
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public Integer getDeleteflag() {
        return deleteflag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column xiaofeiqiandao.deleteFlag
     *
     * @param deleteflag the value for xiaofeiqiandao.deleteFlag
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setDeleteflag(Integer deleteflag) {
        this.deleteflag = deleteflag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column xiaofeiqiandao.erjiguanlianzd
     *
     * @return the value of xiaofeiqiandao.erjiguanlianzd
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getErjiguanlianzd() {
        return erjiguanlianzd;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column xiaofeiqiandao.erjiguanlianzd
     *
     * @param erjiguanlianzd the value for xiaofeiqiandao.erjiguanlianzd
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setErjiguanlianzd(String erjiguanlianzd) {
        this.erjiguanlianzd = erjiguanlianzd;
    }
}