package bean;

public class zhifufangshiBean {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column zhifufangshi.id
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column zhifufangshi.zhifufangshi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String zhifufangshi;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column zhifufangshi.operatorId
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String operatorid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column zhifufangshi.itime
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String itime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column zhifufangshi.detail
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String detail;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column zhifufangshi.deleteFlag
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private Integer deleteflag;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column zhifufangshi.erjiguanlianzd
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String erjiguanlianzd;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column zhifufangshi.id
     *
     * @return the value of zhifufangshi.id
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column zhifufangshi.id
     *
     * @param id the value for zhifufangshi.id
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column zhifufangshi.zhifufangshi
     *
     * @return the value of zhifufangshi.zhifufangshi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getZhifufangshi() {
        return zhifufangshi;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column zhifufangshi.zhifufangshi
     *
     * @param zhifufangshi the value for zhifufangshi.zhifufangshi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setZhifufangshi(String zhifufangshi) {
        this.zhifufangshi = zhifufangshi;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column zhifufangshi.operatorId
     *
     * @return the value of zhifufangshi.operatorId
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getOperatorid() {
        return operatorid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column zhifufangshi.operatorId
     *
     * @param operatorid the value for zhifufangshi.operatorId
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setOperatorid(String operatorid) {
        this.operatorid = operatorid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column zhifufangshi.itime
     *
     * @return the value of zhifufangshi.itime
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getItime() {
        return itime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column zhifufangshi.itime
     *
     * @param itime the value for zhifufangshi.itime
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setItime(String itime) {
        this.itime = itime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column zhifufangshi.detail
     *
     * @return the value of zhifufangshi.detail
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column zhifufangshi.detail
     *
     * @param detail the value for zhifufangshi.detail
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setDetail(String detail) {
        this.detail = detail;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column zhifufangshi.deleteFlag
     *
     * @return the value of zhifufangshi.deleteFlag
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public Integer getDeleteflag() {
        return deleteflag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column zhifufangshi.deleteFlag
     *
     * @param deleteflag the value for zhifufangshi.deleteFlag
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setDeleteflag(Integer deleteflag) {
        this.deleteflag = deleteflag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column zhifufangshi.erjiguanlianzd
     *
     * @return the value of zhifufangshi.erjiguanlianzd
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getErjiguanlianzd() {
        return erjiguanlianzd;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column zhifufangshi.erjiguanlianzd
     *
     * @param erjiguanlianzd the value for zhifufangshi.erjiguanlianzd
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setErjiguanlianzd(String erjiguanlianzd) {
        this.erjiguanlianzd = erjiguanlianzd;
    }
}