package bean;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class zhucehuiyuanBeanExample {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table zhucehuiyuan
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table zhucehuiyuan
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table zhucehuiyuan
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public zhucehuiyuanBeanExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table zhucehuiyuan
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    protected zhucehuiyuanBeanExample(zhucehuiyuanBeanExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table zhucehuiyuan
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table zhucehuiyuan
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table zhucehuiyuan
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table zhucehuiyuan
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table zhucehuiyuan
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table zhucehuiyuan
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table zhucehuiyuan
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table zhucehuiyuan
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public static class Criteria {
        protected List<String> criteriaWithoutValue;

        protected List<Map<String, Object>> criteriaWithSingleValue;

        protected List<Map<String, Object>> criteriaWithListValue;

        protected List<Map<String, Object>> criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList<String>();
            criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
            criteriaWithListValue = new ArrayList<Map<String, Object>>();
            criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List<String> getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List<Map<String, Object>> getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List<Map<String, Object>> getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List<Map<String, Object>> getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List<? extends Object> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List<Object> list = new ArrayList<Object>();
            list.add(value1);
            list.add(value2);
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return this;
        }

        public Criteria andYonghuzhanghaoIsNull() {
            addCriterion("yonghuzhanghao is null");
            return this;
        }

        public Criteria andYonghuzhanghaoIsNotNull() {
            addCriterion("yonghuzhanghao is not null");
            return this;
        }

        public Criteria andYonghuzhanghaoEqualTo(String value) {
            addCriterion("yonghuzhanghao =", value, "yonghuzhanghao");
            return this;
        }

        public Criteria andYonghuzhanghaoNotEqualTo(String value) {
            addCriterion("yonghuzhanghao <>", value, "yonghuzhanghao");
            return this;
        }

        public Criteria andYonghuzhanghaoGreaterThan(String value) {
            addCriterion("yonghuzhanghao >", value, "yonghuzhanghao");
            return this;
        }

        public Criteria andYonghuzhanghaoGreaterThanOrEqualTo(String value) {
            addCriterion("yonghuzhanghao >=", value, "yonghuzhanghao");
            return this;
        }

        public Criteria andYonghuzhanghaoLessThan(String value) {
            addCriterion("yonghuzhanghao <", value, "yonghuzhanghao");
            return this;
        }

        public Criteria andYonghuzhanghaoLessThanOrEqualTo(String value) {
            addCriterion("yonghuzhanghao <=", value, "yonghuzhanghao");
            return this;
        }

        public Criteria andYonghuzhanghaoLike(String value) {
            addCriterion("yonghuzhanghao like", value, "yonghuzhanghao");
            return this;
        }

        public Criteria andYonghuzhanghaoNotLike(String value) {
            addCriterion("yonghuzhanghao not like", value, "yonghuzhanghao");
            return this;
        }

        public Criteria andYonghuzhanghaoIn(List<String> values) {
            addCriterion("yonghuzhanghao in", values, "yonghuzhanghao");
            return this;
        }

        public Criteria andYonghuzhanghaoNotIn(List<String> values) {
            addCriterion("yonghuzhanghao not in", values, "yonghuzhanghao");
            return this;
        }

        public Criteria andYonghuzhanghaoBetween(String value1, String value2) {
            addCriterion("yonghuzhanghao between", value1, value2, "yonghuzhanghao");
            return this;
        }

        public Criteria andYonghuzhanghaoNotBetween(String value1, String value2) {
            addCriterion("yonghuzhanghao not between", value1, value2, "yonghuzhanghao");
            return this;
        }

        public Criteria andHuiyuanleixingIsNull() {
            addCriterion("huiyuanleixing is null");
            return this;
        }

        public Criteria andHuiyuanleixingIsNotNull() {
            addCriterion("huiyuanleixing is not null");
            return this;
        }

        public Criteria andHuiyuanleixingEqualTo(String value) {
            addCriterion("huiyuanleixing =", value, "huiyuanleixing");
            return this;
        }

        public Criteria andHuiyuanleixingNotEqualTo(String value) {
            addCriterion("huiyuanleixing <>", value, "huiyuanleixing");
            return this;
        }

        public Criteria andHuiyuanleixingGreaterThan(String value) {
            addCriterion("huiyuanleixing >", value, "huiyuanleixing");
            return this;
        }

        public Criteria andHuiyuanleixingGreaterThanOrEqualTo(String value) {
            addCriterion("huiyuanleixing >=", value, "huiyuanleixing");
            return this;
        }

        public Criteria andHuiyuanleixingLessThan(String value) {
            addCriterion("huiyuanleixing <", value, "huiyuanleixing");
            return this;
        }

        public Criteria andHuiyuanleixingLessThanOrEqualTo(String value) {
            addCriterion("huiyuanleixing <=", value, "huiyuanleixing");
            return this;
        }

        public Criteria andHuiyuanleixingLike(String value) {
            addCriterion("huiyuanleixing like", value, "huiyuanleixing");
            return this;
        }

        public Criteria andHuiyuanleixingNotLike(String value) {
            addCriterion("huiyuanleixing not like", value, "huiyuanleixing");
            return this;
        }

        public Criteria andHuiyuanleixingIn(List<String> values) {
            addCriterion("huiyuanleixing in", values, "huiyuanleixing");
            return this;
        }

        public Criteria andHuiyuanleixingNotIn(List<String> values) {
            addCriterion("huiyuanleixing not in", values, "huiyuanleixing");
            return this;
        }

        public Criteria andHuiyuanleixingBetween(String value1, String value2) {
            addCriterion("huiyuanleixing between", value1, value2, "huiyuanleixing");
            return this;
        }

        public Criteria andHuiyuanleixingNotBetween(String value1, String value2) {
            addCriterion("huiyuanleixing not between", value1, value2, "huiyuanleixing");
            return this;
        }

        public Criteria andKaishishijianIsNull() {
            addCriterion("kaishishijian is null");
            return this;
        }

        public Criteria andKaishishijianIsNotNull() {
            addCriterion("kaishishijian is not null");
            return this;
        }

        public Criteria andKaishishijianEqualTo(String value) {
            addCriterion("kaishishijian =", value, "kaishishijian");
            return this;
        }

        public Criteria andKaishishijianNotEqualTo(String value) {
            addCriterion("kaishishijian <>", value, "kaishishijian");
            return this;
        }

        public Criteria andKaishishijianGreaterThan(String value) {
            addCriterion("kaishishijian >", value, "kaishishijian");
            return this;
        }

        public Criteria andKaishishijianGreaterThanOrEqualTo(String value) {
            addCriterion("kaishishijian >=", value, "kaishishijian");
            return this;
        }

        public Criteria andKaishishijianLessThan(String value) {
            addCriterion("kaishishijian <", value, "kaishishijian");
            return this;
        }

        public Criteria andKaishishijianLessThanOrEqualTo(String value) {
            addCriterion("kaishishijian <=", value, "kaishishijian");
            return this;
        }

        public Criteria andKaishishijianLike(String value) {
            addCriterion("kaishishijian like", value, "kaishishijian");
            return this;
        }

        public Criteria andKaishishijianNotLike(String value) {
            addCriterion("kaishishijian not like", value, "kaishishijian");
            return this;
        }

        public Criteria andKaishishijianIn(List<String> values) {
            addCriterion("kaishishijian in", values, "kaishishijian");
            return this;
        }

        public Criteria andKaishishijianNotIn(List<String> values) {
            addCriterion("kaishishijian not in", values, "kaishishijian");
            return this;
        }

        public Criteria andKaishishijianBetween(String value1, String value2) {
            addCriterion("kaishishijian between", value1, value2, "kaishishijian");
            return this;
        }

        public Criteria andKaishishijianNotBetween(String value1, String value2) {
            addCriterion("kaishishijian not between", value1, value2, "kaishishijian");
            return this;
        }

        public Criteria andDaoqishijianIsNull() {
            addCriterion("daoqishijian is null");
            return this;
        }

        public Criteria andDaoqishijianIsNotNull() {
            addCriterion("daoqishijian is not null");
            return this;
        }

        public Criteria andDaoqishijianEqualTo(String value) {
            addCriterion("daoqishijian =", value, "daoqishijian");
            return this;
        }

        public Criteria andDaoqishijianNotEqualTo(String value) {
            addCriterion("daoqishijian <>", value, "daoqishijian");
            return this;
        }

        public Criteria andDaoqishijianGreaterThan(String value) {
            addCriterion("daoqishijian >", value, "daoqishijian");
            return this;
        }

        public Criteria andDaoqishijianGreaterThanOrEqualTo(String value) {
            addCriterion("daoqishijian >=", value, "daoqishijian");
            return this;
        }

        public Criteria andDaoqishijianLessThan(String value) {
            addCriterion("daoqishijian <", value, "daoqishijian");
            return this;
        }

        public Criteria andDaoqishijianLessThanOrEqualTo(String value) {
            addCriterion("daoqishijian <=", value, "daoqishijian");
            return this;
        }

        public Criteria andDaoqishijianLike(String value) {
            addCriterion("daoqishijian like", value, "daoqishijian");
            return this;
        }

        public Criteria andDaoqishijianNotLike(String value) {
            addCriterion("daoqishijian not like", value, "daoqishijian");
            return this;
        }

        public Criteria andDaoqishijianIn(List<String> values) {
            addCriterion("daoqishijian in", values, "daoqishijian");
            return this;
        }

        public Criteria andDaoqishijianNotIn(List<String> values) {
            addCriterion("daoqishijian not in", values, "daoqishijian");
            return this;
        }

        public Criteria andDaoqishijianBetween(String value1, String value2) {
            addCriterion("daoqishijian between", value1, value2, "daoqishijian");
            return this;
        }

        public Criteria andDaoqishijianNotBetween(String value1, String value2) {
            addCriterion("daoqishijian not between", value1, value2, "daoqishijian");
            return this;
        }

        public Criteria andShengyucishuIsNull() {
            addCriterion("shengyucishu is null");
            return this;
        }

        public Criteria andShengyucishuIsNotNull() {
            addCriterion("shengyucishu is not null");
            return this;
        }

        public Criteria andShengyucishuEqualTo(String value) {
            addCriterion("shengyucishu =", value, "shengyucishu");
            return this;
        }

        public Criteria andShengyucishuNotEqualTo(String value) {
            addCriterion("shengyucishu <>", value, "shengyucishu");
            return this;
        }

        public Criteria andShengyucishuGreaterThan(String value) {
            addCriterion("shengyucishu >", value, "shengyucishu");
            return this;
        }

        public Criteria andShengyucishuGreaterThanOrEqualTo(String value) {
            addCriterion("shengyucishu >=", value, "shengyucishu");
            return this;
        }

        public Criteria andShengyucishuLessThan(String value) {
            addCriterion("shengyucishu <", value, "shengyucishu");
            return this;
        }

        public Criteria andShengyucishuLessThanOrEqualTo(String value) {
            addCriterion("shengyucishu <=", value, "shengyucishu");
            return this;
        }

        public Criteria andShengyucishuLike(String value) {
            addCriterion("shengyucishu like", value, "shengyucishu");
            return this;
        }

        public Criteria andShengyucishuNotLike(String value) {
            addCriterion("shengyucishu not like", value, "shengyucishu");
            return this;
        }

        public Criteria andShengyucishuIn(List<String> values) {
            addCriterion("shengyucishu in", values, "shengyucishu");
            return this;
        }

        public Criteria andShengyucishuNotIn(List<String> values) {
            addCriterion("shengyucishu not in", values, "shengyucishu");
            return this;
        }

        public Criteria andShengyucishuBetween(String value1, String value2) {
            addCriterion("shengyucishu between", value1, value2, "shengyucishu");
            return this;
        }

        public Criteria andShengyucishuNotBetween(String value1, String value2) {
            addCriterion("shengyucishu not between", value1, value2, "shengyucishu");
            return this;
        }

        public Criteria andZhifufangshiIsNull() {
            addCriterion("zhifufangshi is null");
            return this;
        }

        public Criteria andZhifufangshiIsNotNull() {
            addCriterion("zhifufangshi is not null");
            return this;
        }

        public Criteria andZhifufangshiEqualTo(String value) {
            addCriterion("zhifufangshi =", value, "zhifufangshi");
            return this;
        }

        public Criteria andZhifufangshiNotEqualTo(String value) {
            addCriterion("zhifufangshi <>", value, "zhifufangshi");
            return this;
        }

        public Criteria andZhifufangshiGreaterThan(String value) {
            addCriterion("zhifufangshi >", value, "zhifufangshi");
            return this;
        }

        public Criteria andZhifufangshiGreaterThanOrEqualTo(String value) {
            addCriterion("zhifufangshi >=", value, "zhifufangshi");
            return this;
        }

        public Criteria andZhifufangshiLessThan(String value) {
            addCriterion("zhifufangshi <", value, "zhifufangshi");
            return this;
        }

        public Criteria andZhifufangshiLessThanOrEqualTo(String value) {
            addCriterion("zhifufangshi <=", value, "zhifufangshi");
            return this;
        }

        public Criteria andZhifufangshiLike(String value) {
            addCriterion("zhifufangshi like", value, "zhifufangshi");
            return this;
        }

        public Criteria andZhifufangshiNotLike(String value) {
            addCriterion("zhifufangshi not like", value, "zhifufangshi");
            return this;
        }

        public Criteria andZhifufangshiIn(List<String> values) {
            addCriterion("zhifufangshi in", values, "zhifufangshi");
            return this;
        }

        public Criteria andZhifufangshiNotIn(List<String> values) {
            addCriterion("zhifufangshi not in", values, "zhifufangshi");
            return this;
        }

        public Criteria andZhifufangshiBetween(String value1, String value2) {
            addCriterion("zhifufangshi between", value1, value2, "zhifufangshi");
            return this;
        }

        public Criteria andZhifufangshiNotBetween(String value1, String value2) {
            addCriterion("zhifufangshi not between", value1, value2, "zhifufangshi");
            return this;
        }

        public Criteria andShoulirenIsNull() {
            addCriterion("shouliren is null");
            return this;
        }

        public Criteria andShoulirenIsNotNull() {
            addCriterion("shouliren is not null");
            return this;
        }

        public Criteria andShoulirenEqualTo(String value) {
            addCriterion("shouliren =", value, "shouliren");
            return this;
        }

        public Criteria andShoulirenNotEqualTo(String value) {
            addCriterion("shouliren <>", value, "shouliren");
            return this;
        }

        public Criteria andShoulirenGreaterThan(String value) {
            addCriterion("shouliren >", value, "shouliren");
            return this;
        }

        public Criteria andShoulirenGreaterThanOrEqualTo(String value) {
            addCriterion("shouliren >=", value, "shouliren");
            return this;
        }

        public Criteria andShoulirenLessThan(String value) {
            addCriterion("shouliren <", value, "shouliren");
            return this;
        }

        public Criteria andShoulirenLessThanOrEqualTo(String value) {
            addCriterion("shouliren <=", value, "shouliren");
            return this;
        }

        public Criteria andShoulirenLike(String value) {
            addCriterion("shouliren like", value, "shouliren");
            return this;
        }

        public Criteria andShoulirenNotLike(String value) {
            addCriterion("shouliren not like", value, "shouliren");
            return this;
        }

        public Criteria andShoulirenIn(List<String> values) {
            addCriterion("shouliren in", values, "shouliren");
            return this;
        }

        public Criteria andShoulirenNotIn(List<String> values) {
            addCriterion("shouliren not in", values, "shouliren");
            return this;
        }

        public Criteria andShoulirenBetween(String value1, String value2) {
            addCriterion("shouliren between", value1, value2, "shouliren");
            return this;
        }

        public Criteria andShoulirenNotBetween(String value1, String value2) {
            addCriterion("shouliren not between", value1, value2, "shouliren");
            return this;
        }

        public Criteria andShoulishijianIsNull() {
            addCriterion("shoulishijian is null");
            return this;
        }

        public Criteria andShoulishijianIsNotNull() {
            addCriterion("shoulishijian is not null");
            return this;
        }

        public Criteria andShoulishijianEqualTo(String value) {
            addCriterion("shoulishijian =", value, "shoulishijian");
            return this;
        }

        public Criteria andShoulishijianNotEqualTo(String value) {
            addCriterion("shoulishijian <>", value, "shoulishijian");
            return this;
        }

        public Criteria andShoulishijianGreaterThan(String value) {
            addCriterion("shoulishijian >", value, "shoulishijian");
            return this;
        }

        public Criteria andShoulishijianGreaterThanOrEqualTo(String value) {
            addCriterion("shoulishijian >=", value, "shoulishijian");
            return this;
        }

        public Criteria andShoulishijianLessThan(String value) {
            addCriterion("shoulishijian <", value, "shoulishijian");
            return this;
        }

        public Criteria andShoulishijianLessThanOrEqualTo(String value) {
            addCriterion("shoulishijian <=", value, "shoulishijian");
            return this;
        }

        public Criteria andShoulishijianLike(String value) {
            addCriterion("shoulishijian like", value, "shoulishijian");
            return this;
        }

        public Criteria andShoulishijianNotLike(String value) {
            addCriterion("shoulishijian not like", value, "shoulishijian");
            return this;
        }

        public Criteria andShoulishijianIn(List<String> values) {
            addCriterion("shoulishijian in", values, "shoulishijian");
            return this;
        }

        public Criteria andShoulishijianNotIn(List<String> values) {
            addCriterion("shoulishijian not in", values, "shoulishijian");
            return this;
        }

        public Criteria andShoulishijianBetween(String value1, String value2) {
            addCriterion("shoulishijian between", value1, value2, "shoulishijian");
            return this;
        }

        public Criteria andShoulishijianNotBetween(String value1, String value2) {
            addCriterion("shoulishijian not between", value1, value2, "shoulishijian");
            return this;
        }

        public Criteria andShenpiIsNull() {
            addCriterion("shenpi is null");
            return this;
        }

        public Criteria andShenpiIsNotNull() {
            addCriterion("shenpi is not null");
            return this;
        }

        public Criteria andShenpiEqualTo(String value) {
            addCriterion("shenpi =", value, "shenpi");
            return this;
        }

        public Criteria andShenpiNotEqualTo(String value) {
            addCriterion("shenpi <>", value, "shenpi");
            return this;
        }

        public Criteria andShenpiGreaterThan(String value) {
            addCriterion("shenpi >", value, "shenpi");
            return this;
        }

        public Criteria andShenpiGreaterThanOrEqualTo(String value) {
            addCriterion("shenpi >=", value, "shenpi");
            return this;
        }

        public Criteria andShenpiLessThan(String value) {
            addCriterion("shenpi <", value, "shenpi");
            return this;
        }

        public Criteria andShenpiLessThanOrEqualTo(String value) {
            addCriterion("shenpi <=", value, "shenpi");
            return this;
        }

        public Criteria andShenpiLike(String value) {
            addCriterion("shenpi like", value, "shenpi");
            return this;
        }

        public Criteria andShenpiNotLike(String value) {
            addCriterion("shenpi not like", value, "shenpi");
            return this;
        }

        public Criteria andShenpiIn(List<String> values) {
            addCriterion("shenpi in", values, "shenpi");
            return this;
        }

        public Criteria andShenpiNotIn(List<String> values) {
            addCriterion("shenpi not in", values, "shenpi");
            return this;
        }

        public Criteria andShenpiBetween(String value1, String value2) {
            addCriterion("shenpi between", value1, value2, "shenpi");
            return this;
        }

        public Criteria andShenpiNotBetween(String value1, String value2) {
            addCriterion("shenpi not between", value1, value2, "shenpi");
            return this;
        }

        public Criteria andFujianIsNull() {
            addCriterion("fuJian is null");
            return this;
        }

        public Criteria andFujianIsNotNull() {
            addCriterion("fuJian is not null");
            return this;
        }

        public Criteria andFujianEqualTo(String value) {
            addCriterion("fuJian =", value, "fujian");
            return this;
        }

        public Criteria andFujianNotEqualTo(String value) {
            addCriterion("fuJian <>", value, "fujian");
            return this;
        }

        public Criteria andFujianGreaterThan(String value) {
            addCriterion("fuJian >", value, "fujian");
            return this;
        }

        public Criteria andFujianGreaterThanOrEqualTo(String value) {
            addCriterion("fuJian >=", value, "fujian");
            return this;
        }

        public Criteria andFujianLessThan(String value) {
            addCriterion("fuJian <", value, "fujian");
            return this;
        }

        public Criteria andFujianLessThanOrEqualTo(String value) {
            addCriterion("fuJian <=", value, "fujian");
            return this;
        }

        public Criteria andFujianLike(String value) {
            addCriterion("fuJian like", value, "fujian");
            return this;
        }

        public Criteria andFujianNotLike(String value) {
            addCriterion("fuJian not like", value, "fujian");
            return this;
        }

        public Criteria andFujianIn(List<String> values) {
            addCriterion("fuJian in", values, "fujian");
            return this;
        }

        public Criteria andFujianNotIn(List<String> values) {
            addCriterion("fuJian not in", values, "fujian");
            return this;
        }

        public Criteria andFujianBetween(String value1, String value2) {
            addCriterion("fuJian between", value1, value2, "fujian");
            return this;
        }

        public Criteria andFujianNotBetween(String value1, String value2) {
            addCriterion("fuJian not between", value1, value2, "fujian");
            return this;
        }

        public Criteria andOperatoridIsNull() {
            addCriterion("operatorId is null");
            return this;
        }

        public Criteria andOperatoridIsNotNull() {
            addCriterion("operatorId is not null");
            return this;
        }

        public Criteria andOperatoridEqualTo(String value) {
            addCriterion("operatorId =", value, "operatorid");
            return this;
        }

        public Criteria andOperatoridNotEqualTo(String value) {
            addCriterion("operatorId <>", value, "operatorid");
            return this;
        }

        public Criteria andOperatoridGreaterThan(String value) {
            addCriterion("operatorId >", value, "operatorid");
            return this;
        }

        public Criteria andOperatoridGreaterThanOrEqualTo(String value) {
            addCriterion("operatorId >=", value, "operatorid");
            return this;
        }

        public Criteria andOperatoridLessThan(String value) {
            addCriterion("operatorId <", value, "operatorid");
            return this;
        }

        public Criteria andOperatoridLessThanOrEqualTo(String value) {
            addCriterion("operatorId <=", value, "operatorid");
            return this;
        }

        public Criteria andOperatoridLike(String value) {
            addCriterion("operatorId like", value, "operatorid");
            return this;
        }

        public Criteria andOperatoridNotLike(String value) {
            addCriterion("operatorId not like", value, "operatorid");
            return this;
        }

        public Criteria andOperatoridIn(List<String> values) {
            addCriterion("operatorId in", values, "operatorid");
            return this;
        }

        public Criteria andOperatoridNotIn(List<String> values) {
            addCriterion("operatorId not in", values, "operatorid");
            return this;
        }

        public Criteria andOperatoridBetween(String value1, String value2) {
            addCriterion("operatorId between", value1, value2, "operatorid");
            return this;
        }

        public Criteria andOperatoridNotBetween(String value1, String value2) {
            addCriterion("operatorId not between", value1, value2, "operatorid");
            return this;
        }

        public Criteria andItimeIsNull() {
            addCriterion("itime is null");
            return this;
        }

        public Criteria andItimeIsNotNull() {
            addCriterion("itime is not null");
            return this;
        }

        public Criteria andItimeEqualTo(String value) {
            addCriterion("itime =", value, "itime");
            return this;
        }

        public Criteria andItimeNotEqualTo(String value) {
            addCriterion("itime <>", value, "itime");
            return this;
        }

        public Criteria andItimeGreaterThan(String value) {
            addCriterion("itime >", value, "itime");
            return this;
        }

        public Criteria andItimeGreaterThanOrEqualTo(String value) {
            addCriterion("itime >=", value, "itime");
            return this;
        }

        public Criteria andItimeLessThan(String value) {
            addCriterion("itime <", value, "itime");
            return this;
        }

        public Criteria andItimeLessThanOrEqualTo(String value) {
            addCriterion("itime <=", value, "itime");
            return this;
        }

        public Criteria andItimeLike(String value) {
            addCriterion("itime like", value, "itime");
            return this;
        }

        public Criteria andItimeNotLike(String value) {
            addCriterion("itime not like", value, "itime");
            return this;
        }

        public Criteria andItimeIn(List<String> values) {
            addCriterion("itime in", values, "itime");
            return this;
        }

        public Criteria andItimeNotIn(List<String> values) {
            addCriterion("itime not in", values, "itime");
            return this;
        }

        public Criteria andItimeBetween(String value1, String value2) {
            addCriterion("itime between", value1, value2, "itime");
            return this;
        }

        public Criteria andItimeNotBetween(String value1, String value2) {
            addCriterion("itime not between", value1, value2, "itime");
            return this;
        }

        public Criteria andDetailIsNull() {
            addCriterion("detail is null");
            return this;
        }

        public Criteria andDetailIsNotNull() {
            addCriterion("detail is not null");
            return this;
        }

        public Criteria andDetailEqualTo(String value) {
            addCriterion("detail =", value, "detail");
            return this;
        }

        public Criteria andDetailNotEqualTo(String value) {
            addCriterion("detail <>", value, "detail");
            return this;
        }

        public Criteria andDetailGreaterThan(String value) {
            addCriterion("detail >", value, "detail");
            return this;
        }

        public Criteria andDetailGreaterThanOrEqualTo(String value) {
            addCriterion("detail >=", value, "detail");
            return this;
        }

        public Criteria andDetailLessThan(String value) {
            addCriterion("detail <", value, "detail");
            return this;
        }

        public Criteria andDetailLessThanOrEqualTo(String value) {
            addCriterion("detail <=", value, "detail");
            return this;
        }

        public Criteria andDetailLike(String value) {
            addCriterion("detail like", value, "detail");
            return this;
        }

        public Criteria andDetailNotLike(String value) {
            addCriterion("detail not like", value, "detail");
            return this;
        }

        public Criteria andDetailIn(List<String> values) {
            addCriterion("detail in", values, "detail");
            return this;
        }

        public Criteria andDetailNotIn(List<String> values) {
            addCriterion("detail not in", values, "detail");
            return this;
        }

        public Criteria andDetailBetween(String value1, String value2) {
            addCriterion("detail between", value1, value2, "detail");
            return this;
        }

        public Criteria andDetailNotBetween(String value1, String value2) {
            addCriterion("detail not between", value1, value2, "detail");
            return this;
        }

        public Criteria andDeleteflagIsNull() {
            addCriterion("deleteFlag is null");
            return this;
        }

        public Criteria andDeleteflagIsNotNull() {
            addCriterion("deleteFlag is not null");
            return this;
        }

        public Criteria andDeleteflagEqualTo(Integer value) {
            addCriterion("deleteFlag =", value, "deleteflag");
            return this;
        }

        public Criteria andDeleteflagNotEqualTo(Integer value) {
            addCriterion("deleteFlag <>", value, "deleteflag");
            return this;
        }

        public Criteria andDeleteflagGreaterThan(Integer value) {
            addCriterion("deleteFlag >", value, "deleteflag");
            return this;
        }

        public Criteria andDeleteflagGreaterThanOrEqualTo(Integer value) {
            addCriterion("deleteFlag >=", value, "deleteflag");
            return this;
        }

        public Criteria andDeleteflagLessThan(Integer value) {
            addCriterion("deleteFlag <", value, "deleteflag");
            return this;
        }

        public Criteria andDeleteflagLessThanOrEqualTo(Integer value) {
            addCriterion("deleteFlag <=", value, "deleteflag");
            return this;
        }

        public Criteria andDeleteflagIn(List<Integer> values) {
            addCriterion("deleteFlag in", values, "deleteflag");
            return this;
        }

        public Criteria andDeleteflagNotIn(List<Integer> values) {
            addCriterion("deleteFlag not in", values, "deleteflag");
            return this;
        }

        public Criteria andDeleteflagBetween(Integer value1, Integer value2) {
            addCriterion("deleteFlag between", value1, value2, "deleteflag");
            return this;
        }

        public Criteria andDeleteflagNotBetween(Integer value1, Integer value2) {
            addCriterion("deleteFlag not between", value1, value2, "deleteflag");
            return this;
        }

        public Criteria andErjiguanlianzdIsNull() {
            addCriterion("erjiguanlianzd is null");
            return this;
        }

        public Criteria andErjiguanlianzdIsNotNull() {
            addCriterion("erjiguanlianzd is not null");
            return this;
        }

        public Criteria andErjiguanlianzdEqualTo(String value) {
            addCriterion("erjiguanlianzd =", value, "erjiguanlianzd");
            return this;
        }

        public Criteria andErjiguanlianzdNotEqualTo(String value) {
            addCriterion("erjiguanlianzd <>", value, "erjiguanlianzd");
            return this;
        }

        public Criteria andErjiguanlianzdGreaterThan(String value) {
            addCriterion("erjiguanlianzd >", value, "erjiguanlianzd");
            return this;
        }

        public Criteria andErjiguanlianzdGreaterThanOrEqualTo(String value) {
            addCriterion("erjiguanlianzd >=", value, "erjiguanlianzd");
            return this;
        }

        public Criteria andErjiguanlianzdLessThan(String value) {
            addCriterion("erjiguanlianzd <", value, "erjiguanlianzd");
            return this;
        }

        public Criteria andErjiguanlianzdLessThanOrEqualTo(String value) {
            addCriterion("erjiguanlianzd <=", value, "erjiguanlianzd");
            return this;
        }

        public Criteria andErjiguanlianzdLike(String value) {
            addCriterion("erjiguanlianzd like", value, "erjiguanlianzd");
            return this;
        }

        public Criteria andErjiguanlianzdNotLike(String value) {
            addCriterion("erjiguanlianzd not like", value, "erjiguanlianzd");
            return this;
        }

        public Criteria andErjiguanlianzdIn(List<String> values) {
            addCriterion("erjiguanlianzd in", values, "erjiguanlianzd");
            return this;
        }

        public Criteria andErjiguanlianzdNotIn(List<String> values) {
            addCriterion("erjiguanlianzd not in", values, "erjiguanlianzd");
            return this;
        }

        public Criteria andErjiguanlianzdBetween(String value1, String value2) {
            addCriterion("erjiguanlianzd between", value1, value2, "erjiguanlianzd");
            return this;
        }

        public Criteria andErjiguanlianzdNotBetween(String value1, String value2) {
            addCriterion("erjiguanlianzd not between", value1, value2, "erjiguanlianzd");
            return this;
        }
    }
}