package bean;

public class zhucehuiyuanBean {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column zhucehuiyuan.id
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column zhucehuiyuan.yonghuzhanghao
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String yonghuzhanghao;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column zhucehuiyuan.huiyuanleixing
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String huiyuanleixing;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column zhucehuiyuan.kaishishijian
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String kaishishijian;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column zhucehuiyuan.daoqishijian
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String daoqishijian;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column zhucehuiyuan.shengyucishu
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String shengyucishu;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column zhucehuiyuan.zhifufangshi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String zhifufangshi;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column zhucehuiyuan.shouliren
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String shouliren;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column zhucehuiyuan.shoulishijian
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String shoulishijian;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column zhucehuiyuan.shenpi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String shenpi;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column zhucehuiyuan.fuJian
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String fujian;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column zhucehuiyuan.operatorId
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String operatorid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column zhucehuiyuan.itime
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String itime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column zhucehuiyuan.detail
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String detail;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column zhucehuiyuan.deleteFlag
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private Integer deleteflag;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column zhucehuiyuan.erjiguanlianzd
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    private String erjiguanlianzd;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column zhucehuiyuan.id
     *
     * @return the value of zhucehuiyuan.id
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column zhucehuiyuan.id
     *
     * @param id the value for zhucehuiyuan.id
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column zhucehuiyuan.yonghuzhanghao
     *
     * @return the value of zhucehuiyuan.yonghuzhanghao
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getYonghuzhanghao() {
        return yonghuzhanghao;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column zhucehuiyuan.yonghuzhanghao
     *
     * @param yonghuzhanghao the value for zhucehuiyuan.yonghuzhanghao
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setYonghuzhanghao(String yonghuzhanghao) {
        this.yonghuzhanghao = yonghuzhanghao;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column zhucehuiyuan.huiyuanleixing
     *
     * @return the value of zhucehuiyuan.huiyuanleixing
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getHuiyuanleixing() {
        return huiyuanleixing;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column zhucehuiyuan.huiyuanleixing
     *
     * @param huiyuanleixing the value for zhucehuiyuan.huiyuanleixing
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setHuiyuanleixing(String huiyuanleixing) {
        this.huiyuanleixing = huiyuanleixing;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column zhucehuiyuan.kaishishijian
     *
     * @return the value of zhucehuiyuan.kaishishijian
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getKaishishijian() {
        return kaishishijian;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column zhucehuiyuan.kaishishijian
     *
     * @param kaishishijian the value for zhucehuiyuan.kaishishijian
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setKaishishijian(String kaishishijian) {
        this.kaishishijian = kaishishijian;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column zhucehuiyuan.daoqishijian
     *
     * @return the value of zhucehuiyuan.daoqishijian
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getDaoqishijian() {
        return daoqishijian;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column zhucehuiyuan.daoqishijian
     *
     * @param daoqishijian the value for zhucehuiyuan.daoqishijian
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setDaoqishijian(String daoqishijian) {
        this.daoqishijian = daoqishijian;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column zhucehuiyuan.shengyucishu
     *
     * @return the value of zhucehuiyuan.shengyucishu
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getShengyucishu() {
        return shengyucishu;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column zhucehuiyuan.shengyucishu
     *
     * @param shengyucishu the value for zhucehuiyuan.shengyucishu
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setShengyucishu(String shengyucishu) {
        this.shengyucishu = shengyucishu;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column zhucehuiyuan.zhifufangshi
     *
     * @return the value of zhucehuiyuan.zhifufangshi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getZhifufangshi() {
        return zhifufangshi;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column zhucehuiyuan.zhifufangshi
     *
     * @param zhifufangshi the value for zhucehuiyuan.zhifufangshi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setZhifufangshi(String zhifufangshi) {
        this.zhifufangshi = zhifufangshi;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column zhucehuiyuan.shouliren
     *
     * @return the value of zhucehuiyuan.shouliren
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getShouliren() {
        return shouliren;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column zhucehuiyuan.shouliren
     *
     * @param shouliren the value for zhucehuiyuan.shouliren
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setShouliren(String shouliren) {
        this.shouliren = shouliren;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column zhucehuiyuan.shoulishijian
     *
     * @return the value of zhucehuiyuan.shoulishijian
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getShoulishijian() {
        return shoulishijian;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column zhucehuiyuan.shoulishijian
     *
     * @param shoulishijian the value for zhucehuiyuan.shoulishijian
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setShoulishijian(String shoulishijian) {
        this.shoulishijian = shoulishijian;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column zhucehuiyuan.shenpi
     *
     * @return the value of zhucehuiyuan.shenpi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getShenpi() {
        return shenpi;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column zhucehuiyuan.shenpi
     *
     * @param shenpi the value for zhucehuiyuan.shenpi
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setShenpi(String shenpi) {
        this.shenpi = shenpi;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column zhucehuiyuan.fuJian
     *
     * @return the value of zhucehuiyuan.fuJian
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getFujian() {
        return fujian;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column zhucehuiyuan.fuJian
     *
     * @param fujian the value for zhucehuiyuan.fuJian
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setFujian(String fujian) {
        this.fujian = fujian;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column zhucehuiyuan.operatorId
     *
     * @return the value of zhucehuiyuan.operatorId
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getOperatorid() {
        return operatorid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column zhucehuiyuan.operatorId
     *
     * @param operatorid the value for zhucehuiyuan.operatorId
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setOperatorid(String operatorid) {
        this.operatorid = operatorid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column zhucehuiyuan.itime
     *
     * @return the value of zhucehuiyuan.itime
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getItime() {
        return itime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column zhucehuiyuan.itime
     *
     * @param itime the value for zhucehuiyuan.itime
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setItime(String itime) {
        this.itime = itime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column zhucehuiyuan.detail
     *
     * @return the value of zhucehuiyuan.detail
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column zhucehuiyuan.detail
     *
     * @param detail the value for zhucehuiyuan.detail
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setDetail(String detail) {
        this.detail = detail;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column zhucehuiyuan.deleteFlag
     *
     * @return the value of zhucehuiyuan.deleteFlag
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public Integer getDeleteflag() {
        return deleteflag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column zhucehuiyuan.deleteFlag
     *
     * @param deleteflag the value for zhucehuiyuan.deleteFlag
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setDeleteflag(Integer deleteflag) {
        this.deleteflag = deleteflag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column zhucehuiyuan.erjiguanlianzd
     *
     * @return the value of zhucehuiyuan.erjiguanlianzd
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public String getErjiguanlianzd() {
        return erjiguanlianzd;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column zhucehuiyuan.erjiguanlianzd
     *
     * @param erjiguanlianzd the value for zhucehuiyuan.erjiguanlianzd
     *
     * @ibatorgenerated Tue Dec 26 10:25:44 CST 2017
     */
    public void setErjiguanlianzd(String erjiguanlianzd) {
        this.erjiguanlianzd = erjiguanlianzd;
    }
}